/* Dashboard-wide acronym glossary. Single source of truth for the hover
   expansions the client decorator (src/scripts/acronyms-client.ts) attaches to
   inline prose and source copy on every tab. Merged from the former per-tab
   maps (legislation, data, hardening, workforce, quality, units) plus the
   governance entity roster (gov.ts codes) and the external bodies cited across
   the health, tax, ltc, medications, and overview tabs.

   Keep values free of em dashes (site rule) and free of source-document codes.
   Add an entry here rather than in a tab-local map so the hover shows up
   everywhere the acronym appears. */

export const ACRONYMS: Record<string, string> = {
  "A1-HCAC": "Article I Health Claims and Appeals Court",
  "AAMC": "Association of American Medical Colleges",
  "AARP": "AARP, an advocacy organization for older Americans",
  "ACA": "Affordable Care Act",
  "ACDRH": "Administration for Care Delivery and Regional Health",
  "AHIRC": "Administration for Health Information, Records, and Cybersecurity",
  "AHWCS": "Administration for Health Workforce, Compensation, and Scope",
  "AI": "Artificial Intelligence",
  "AICIO": "Artificial Intelligence Clinical Integration Office",
  "AJPH": "American Journal of Public Health",
  "AMA": "American Medical Association",
  "AMDDT": "Administration for Medicines, Devices, Diagnostics, and Therapeutics",
  "APA": "Administrative Procedure Act",
  "API": "Application Programming Interface",
  "ARPA-H": "Advanced Research Projects Agency for Health",
  "ASPE": "Office of the Assistant Secretary for Planning and Evaluation",
  "BARDA": "Biomedical Advanced Research and Development Authority",
  "BH": "Behavioral Health",
  "BLS": "Bureau of Labor Statistics",
  "BPCIA": "Biologics Price Competition and Innovation Act",
  "CBC": "Complete Blood Count",
  "CBO": "Congressional Budget Office",
  "CDC": "Centers for Disease Control and Prevention",
  "CES": "Consumer Expenditure Survey",
  "CEVI": "Comparative Effectiveness and Value Institute",
  "CFR": "Code of Federal Regulations",
  "CHAMPVA": "Civilian Health and Medical Program of the Department of Veterans Affairs",
  "CHAO": "Congressional Health Accountability Office",
  "CHIP": "Children's Health Insurance Program",
  "CIRBAS": "Clinician Identity and Role-Based Access System",
  "CIRCIA": "Cyber Incident Reporting for Critical Infrastructure Act",
  "CISA": "Cybersecurity and Infrastructure Security Agency",
  "CLIA": "Clinical Laboratory Improvement Amendments",
  "CMS": "Centers for Medicare & Medicaid Services",
  "COBRA": "Consolidated Omnibus Budget Reconciliation Act",
  "CONG": "Congress (statutory design authority)",
  "CP": "Cost Parameter",
  "CRS": "Congressional Research Service",
  "DME": "Durable Medical Equipment",
  "DMRCO": "Data Migration and Records Continuity Office",
  "DNHA": "Department of National Health Assurance",
  "DNHA-SEC": "Office of the Secretary",
  "DOJ": "Department of Justice",
  "DUSO": "Drug Utilization and Safety Office",
  "DVH": "Dental, Vision, and Hearing",
  "ECG": "Electrocardiogram",
  "ED": "Emergency Department",
  "EH": "Executive-hardening control",
  "EHR": "Electronic Health Record",
  "EMS": "Emergency Medical Services",
  "EMTALA": "Emergency Medical Treatment and Labor Act",
  "ENT": "Ear, nose, and throat",
  "EPTO": "Employer and Payroll Transition Office",
  "ERISA": "Employee Retirement Income Security Act",
  "EU": "European Union",
  "FA": "Specified assumption",
  "FMEA": "Failure Modes and Effects Analysis",
  "FCRA": "Fair Credit Reporting Act",
  "FDA": "Food and Drug Administration",
  "FDCA": "Federal Food, Drug, and Cosmetic Act",
  "FDCPA": "Fair Debt Collection Practices Act",
  "FEHBA": "Federal Employees Health Benefits Act",
  "FISMA": "Federal Information Security Modernization Act",
  "FLSA": "Fair Labor Standards Act",
  "FOIA": "Freedom of Information Act",
  "FQHC": "Federally Qualified Health Center",
  "FTC": "Federal Trade Commission",
  "FTE": "Full-Time Equivalent",
  "GAO": "Government Accountability Office",
  "GDP": "Gross Domestic Product",
  "GME": "Graduate Medical Education",
  "HAAO": "Hospital Administrative Accountability Office",
  "HATC": "Health Administration Transition Corps",
  "HCBS": "Home and Community-Based Services",
  "HCCA": "Health Cybersecurity and Continuity Authority",
  "HCRB": "Health Credential Recognition Board",
  "HESSO": "Hospital and Essential Service Stabilization Office",
  "HFASB": "Health Financing Actuary and Stabilization Board",
  "HHS": "Department of Health and Human Services",
  "HIPAA": "Health Insurance Portability and Accountability Act",
  "HITECH": "Health Information Technology for Economic and Clinical Health Act",
  "HIV": "Human Immunodeficiency Virus",
  "HPSA": "Health Professional Shortage Area",
  "HRPO": "Health Rights and Privacy Office",
  "HRSA": "Health Resources and Services Administration",
  "HSA": "Health Savings Account",
  "HTIP": "Health Talent Immigration Pathway",
  "ICU": "Intensive Care Unit",
  "IEN": "Internationally Educated Nurse",
  "IHS": "Indian Health Service",
  "IMG": "International Medical Graduate",
  "INA": "Immigration and Nationality Act",
  "IRA": "Inflation Reduction Act",
  "IRC": "Internal Revenue Code",
  "IRS": "Internal Revenue Service",
  "IRS-EWTAO": "IRS Extreme Wealth Tax Administration Office",
  "IT": "Information Technology",
  "JAMA": "Journal of the American Medical Association",
  "JCT": "Joint Committee on Taxation",
  "KFF": "KFF, a health policy research organization",
  "KPP": "Key Performance Parameter",
  "LDA": "Laboratory and Diagnostics Authority",
  "LPN": "Licensed Practical Nurse",
  "LPWO": "Legacy Payer Wind-Down Office",
  "LTC": "Long-Term Care",
  "LTSS": "Long-Term Services and Supports",
  "MARB": "Medicine Access Review Board",
  "MAT": "Medication-Assisted Treatment",
  "MDSA": "Medical Device and Supply Authority",
  "MHPAEA": "Mental Health Parity and Addiction Equity Act",
  "MRI": "Magnetic Resonance Imaging",
  "MUA": "Medically Underserved Area",
  "MUP": "Medically Underserved Population",
  "NAIG": "National API and Interoperability Gateway",
  "NAT": "National Appeals Tribunal",
  "NBHA": "National Behavioral Health Authority",
  "NBIA": "National Biomedical Innovation Agency",
  "NCCA": "National Coverage and Claims Authority",
  "NCDSO": "National Clinical Data Standards Office",
  "NCDTN": "National Community Diagnostic and Treatment Network",
  "NCSWB": "National Clinical Scope and Workforce Board",
  "NDIF": "National Drug Innovation Fund",
  "NDPA": "National Drug Purchasing Authority",
  "NDVHO": "National Dental, Vision, and Hearing Benefit Office",
  "NEEA": "National Enrollment and Eligibility Authority",
  "NEMTA": "National EMS and Medical Transport Authority",
  "NFTSB": "National Formulary and Therapeutic Schedule Board",
  "NHA": "National Health Assurance",
  "NHA-TRUST": "National Health Assurance Trust",
  "NHAC": "National Health Accountability Commission",
  "NHAMCS": "National Hospital Ambulatory Medical Care Survey",
  "NHASB": "National Health Adaptation and Scorekeeping Board",
  "NHE": "National Health Expenditures",
  "NHETF": "National Health Equalization Trust Fund",
  "NHI": "National Health Insurance",
  "NHIS": "National Health Identifier Service",
  "NHRA": "National Health Records Authority",
  "NHSA": "National Hospital Stewardship Authority",
  "NHTCA": "National Health Transition and Continuity Authority",
  "NHTIB": "National Health Talent Immigration Board",
  "NHWB": "National Health Workforce Board",
  "NHWECA": "National Health Workforce Education and Capacity Authority",
  "NIH": "National Institutes of Health",
  "NLLHR": "National Longitudinal Health Record",
  "NLRA": "National Labor Relations Act",
  "NLTCA": "National Long-Term Care Authority",
  "NMPI": "National Master Patient Index",
  "NOPRSL": "National Office of Patient Rights, Safety, and Legitimacy",
  "NP": "Nurse practitioner",
  "NPCB": "National Physician Compensation Board",
  "NPHPA": "National Public Health and Prevention Authority",
  "NPSMIB": "National Patient Safety and Medical Injury Board",
  "NRLS": "National Record Locator Service",
  "NSAA": "National Specialty Access Authority",
  "OASDI": "Old-Age, Survivors, and Disability Insurance",
  "OBBBA": "One Big Beautiful Bill Act",
  "OCDTI": "Office of Community Diagnostic and Treatment Infrastructure",
  "OECD": "Organisation for Economic Co-operation and Development",
  "OI": "Open Issue",
  "OIG": "Office of Inspector General",
  "OIG-AF": "Office of Inspector General and Anti-Fraud",
  "OMB": "Office of Management and Budget",
  "ONC": "Office of the National Coordinator for Health Information Technology",
  "OOP": "Out-of-Pocket",
  "PA": "Physician assistant",
  "PACE": "Program of All-Inclusive Care for the Elderly",
  "PACP": "Patient Access and Consent Portal",
  "PBM": "Pharmacy Benefit Manager",
  "PCE": "Personal Consumption Expenditures",
  "PCO": "Patient Continuity Office",
  "PCU": "National Pharmacy Claims Utility",
  "PDCO": "Pharmacy and Drug Continuity Office",
  "PHI": "PHI, a direct-care workforce research organization",
  "PHSA": "Public Health Service Act",
  "PILO": "Public-Interest Licensing Office",
  "PLCCO": "Provider Liquidity and Claims Continuity Office",
  "PMC": "Public Medicines Corporation",
  "PPCO": "Private Plan Certification Office",
  "PREP": "Public Readiness and Emergency Preparedness Act",
  "PROO": "Patient Rights and Ombudsman Office",
  "PRTO": "Public Reporting and Transparency Office",
  "PSHCO": "Public Service Hospital Charter Office",
  "RAND": "RAND Corporation",
  "RFRA": "Religious Freedom Restoration Act",
  "RHA": "Regional Health Administrators",
  "RIF": "Reduction in force",
  "RN": "Registered Nurse",
  "ROI": "Return on Investment",
  "RPN": "Risk Priority Number",
  "RS-CORPS": "Rural Service Corps",
  "SAMHSA": "Substance Abuse and Mental Health Services Administration",
  "SCF": "Survey of Consumer Finances",
  "SOI": "Statistics of Income",
  "SR": "System requirement",
  "SR-DATA": "System Requirement, Data",
  "SRAE": "Secure Research and Analytics Enclave",
  "SRCO": "State and Regional Compact Office",
  "STI": "Sexually Transmitted Infection",
  "SUD": "Substance Use Disorder",
  "TBD": "To Be Determined",
  "THDO": "Treasury Health Disbursement Office",
  "TLSHO": "Transition Legal Safe Harbor Office",
  "TMTFO": "Translational Medicine and Trial Funding Office",
  "TPC": "Tax Policy Center",
  "TPP": "Technical Performance Parameter",
  "TREAS": "Department of the Treasury",
  "TRICARE": "Department of Defense health program for service members, retirees, and families",
  "TRPGO": "Transition Risk and Phase-Gate Office",
  "TRTO": "Tribal and Rural Transition Office",
  "USC": "United States Code",
  "USD": "United States Dollars",
  "UTI": "Urinary tract infection",
  "VA": "Department of Veterans Affairs",
  "VAT": "Value-Added Tax",
  "VHA": "Veterans Health Administration",
  "WARN": "Worker Adjustment and Retraining Notification Act",
  "WHO": "World Health Organization",
};

/* Matcher for standalone acronyms in a run of text. Longest keys first so
   "SR-DATA" wins over "SR"; the lookbehind and lookahead reject an adjacent
   word char, ampersand, slash, or hyphen so a key is never wrapped when it is
   really a fragment of a longer code ("CP" inside "CP-POP-004"). Exposed so the
   client decorator and its test share one definition. */
export function acronymPattern(): RegExp {
  const keys = Object.keys(ACRONYMS).sort((a, b) => b.length - a.length);
  const escaped = keys.map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  return new RegExp('(?<![\\w&/-])(' + escaped.join('|') + ')(?![\\w&/-])', 'g');
}
