/* R271 [§S0]: compare the committed file manifest against the working tree.
 *
 * The audit that produced this backlog could not enumerate a directory: the
 * git trees API, the Contents API and the HTML tree view all returned empty,
 * so its only discovery mechanism was seeing a file named inside another file.
 * That mechanism missed two entire public chapters (ltc, risk), the route
 * registry that enumerates every chapter (tabs.ts), and 23 files that are named
 * in neither audit document.
 *
 * Build-time only. Imported by selftests.ts, which runs in Node during
 * `astro build` and under vitest; nothing in src/scripts/ imports it, so
 * node:fs never reaches a client bundle.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CARE_SCENARIOS } from './care';
import { FILE_MANIFEST } from './file-manifest';
import { TABS } from './tabs';

/* src/lib/manifest-check.ts -> repo root */
const REPO_ROOT = fileURLToPath(new URL('../..', import.meta.url));

export const MANIFEST_ROOTS = ['src', 'tools', 'research'];

/* Not source, and regenerated by anyone who runs a tools/*.py generator, so
   listing it would make the manifest drift on every run. Mirrors .gitignore. */
const IGNORED_DIRS = new Set(['__pycache__']);

/* Memoised per root. These run inside self-tests, which vitest re-imports once
   per test file; without the cache the suite spends minutes re-walking the tree
   and re-reading a 119 KB catalog. */
const fileCache = new Map<string, string[]>();

export function enumerateSourceFiles(root = REPO_ROOT): string[] {
  const hit = fileCache.get(root);
  if (hit) return hit;
  const out: string[] = [];
  for (const dir of MANIFEST_ROOTS) walk(join(root, dir), root, out);
  out.sort();
  fileCache.set(root, out);
  return out;
}

function walk(dir: string, root: string, out: string[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return; /* a root that does not exist is reported as drift, not a crash */
  }
  for (const name of entries) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      if (!IGNORED_DIRS.has(name)) walk(full, root, out);
    }
    else out.push(relative(root, full).split(sep).join('/'));
  }
}

export interface ManifestDrift {
  unlisted: string[]; /* on disk, absent from the manifest */
  missing: string[]; /* in the manifest, absent from disk */
}

export function manifestDrift(actual: string[] = enumerateSourceFiles()): ManifestDrift {
  const listed = new Set(FILE_MANIFEST);
  const onDisk = new Set(actual);
  return {
    unlisted: actual.filter((p) => !listed.has(p)),
    missing: FILE_MANIFEST.filter((p) => !onDisk.has(p))
  };
}

/* R277 [§S3]: the target parser has one implementation.
 *
 * phase-targets.ts owned the original, equations.ts imported it, and fmea.ts
 * reimplemented it under a comment reading "mirrors phase-targets.ts
 * parseNum". Two implementations, three consumers, nothing asserting they
 * agreed - so every robustness concern about the parser applied twice,
 * independently, and the copies could drift without a symptom.
 *
 * A source scan rather than a runtime comparison, because the failure mode is
 * a second implementation existing at all. Comparing outputs would only catch
 * a copy that had ALREADY diverged. */
/* Both declaration forms, because a copy written as an arrow constant would
   otherwise pass a scan that only knows the `function` keyword. Exported so
   the test can exercise the pattern directly rather than re-deriving it. */
export const PARSER_DEFINITION_SOURCE =
  String.raw`\bfunction parseNum\s*\(|\b(?:const|let|var)\s+parseNum\s*(?::[^=]+)?=`;
const PARSER_DEFINITION = new RegExp(PARSER_DEFINITION_SOURCE, 'g');
export const PARSER_HOME = 'src/lib/phase-targets.ts';

export function parserImplementations(root = REPO_ROOT): string[] {
  const out: string[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/') || !rel.endsWith('.ts')) continue;
    const text = readFileSync(join(root, rel), 'utf8');
    /* The repo-relative path, not a slice: the scan covers all of src/, and
       slicing 'src/lib/'.length off a src/scripts/ hit reported it as
       "ipts/foo.ts". The gate still fired on the count, but the note lied
       about where the copy was, which is the only thing the note is for. */
    for (const _ of text.matchAll(PARSER_DEFINITION)) out.push(rel);
  }
  return out.sort();
}

/* R157 [§S5]: the baseline PHC category split, defined once.
 *
 * `hosp0 = B.hospital - 0.6 * e` and `clin0 = B.physician + B.otherProf -
 * 0.4 * e` were written out in three places - runPath, matureAtScale and
 * bridge.ts - each with its own copy of the 0.6/0.4 embedded-drug literals.
 * The bridge identity catches a bridge.ts <-> runPath divergence; nothing
 * caught runPath <-> matureAtScale except one self-test that runs only under
 * `{}` structural.
 *
 * The split now lives in `baselineCategorySplit` and the literals are named
 * constants. This scan makes that a rule: an arithmetic combination of
 * `B.hospital` or `B.physician` with an embedded-drug term may appear only in
 * model.ts, where the shared function is. Comments are masked, so the
 * explanation above and the ones in model.ts do not trip it. */
export const SPLIT_HOME = 'src/lib/model.ts';
export const SPLIT_LITERAL_SOURCE =
  String.raw`B\.hospital\s*-|B\.otherProf\s*-|B\.rxRetail\s*\+`;
const SPLIT_LITERAL = new RegExp(SPLIT_LITERAL_SOURCE, 'g');

export function baselineSplitCopies(root = REPO_ROOT): CodeReference[] {
  return scanSourceLines(SPLIT_LITERAL, { skip: [SPLIT_HOME] }, root);
}

/* R38 [§S5]: a display-only dataset must stay out of the revenue engine.
 *
 * `WEALTH_DIST` carries Fed DFA 2026:Q1 NOMINAL levels inside a 2024$ model.
 * The row's concern is not the label - it is that "nothing currently prevents
 * a later join". A label cannot prevent one; an import check can. Every
 * dataset `taxparams.ts` declares as `computes: false` is scanned for here,
 * and finding one named inside the engine fails the build.
 *
 * `taxmodel.ts` is the whole revenue engine, so its import list is the seam.
 * The display layer (`tax-client.ts`, `tax-charts.ts`) may import whatever it
 * likes; that is what display-only means.
 *
 * The IMPORT LIST, not the file text. The first version scanned the whole
 * masked source and reported all three display-only datasets, because the
 * vintage self-test in that file names them in a string array. Importing a
 * dataset is what makes a join possible; naming it in a check is the opposite
 * of a join. */
export const REVENUE_ENGINE = 'src/lib/taxmodel.ts';
const TAXPARAMS_IMPORT = /import\s*\{([^}]*)\}\s*from\s*'\.\/taxparams'/g;

export function engineImportsFromParams(root = REPO_ROOT): string[] {
  const masked = maskComments(readFileSync(join(root, REVENUE_ENGINE), 'utf8'));
  const names: string[] = [];
  for (const m of masked.matchAll(TAXPARAMS_IMPORT)) {
    m[1].split(',').forEach((raw) => {
      const name = raw.trim().split(/\s+as\s+/)[0].trim();
      if (name) names.push(name);
    });
  }
  return names;
}

export function displayOnlyDatasetsInEngine(
  displayOnly: string[],
  root = REPO_ROOT
): string[] {
  const imported = new Set(engineImportsFromParams(root));
  return displayOnly.filter((id) => imported.has(id));
}

/* R217 [§S5]: no page types a household count.
 *
 * `tax.astro` wrote "the 13,200 households of the top 0.01%" in the
 * DISTRIBUTIONAL section - the WEALTH_DIST figure, which drives the inequality
 * chart - while describing the chart that runs on GROUPS.t10000, 12,000. Both
 * numbers are right about their own series; the prose named the wrong one. It
 * is the fifth household-count inconsistency the audit has found (F1, R172,
 * R184, now this), so the fix is a rule rather than an edit.
 *
 * Any four-or-more-digit figure immediately followed by "household" on a page
 * is a count that should have come from the series it describes. Astro
 * expressions are rendered at build time, so a derived count never appears in
 * the source as a literal and never trips this.
 */
/* An .astro file's leading `---` fence pair, blanked so line numbers survive. */
export function frontmatterStripped(text: string): string {
  if (!text.startsWith('---')) return text;
  const end = text.indexOf('\n---', 3);
  if (end < 0) return text;
  const head = text.slice(0, end + 4);
  return head.replace(/[^\n]/g, ' ') + text.slice(end + 4);
}

export const HOUSEHOLD_LITERAL_SOURCE =
  String.raw`\b\d{1,3}(?:,\d{3})+\s+households?\b|\b\d{4,}\s+households?\b`;
const HOUSEHOLD_LITERAL = new RegExp(HOUSEHOLD_LITERAL_SOURCE, 'g');

export function typedHouseholdCounts(root = REPO_ROOT): CodeReference[] {
  const out: CodeReference[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/pages/') || !rel.endsWith('.astro')) continue;
    const raw = readFileSync(join(root, rel), 'utf8');
    /* The rendered body only. An .astro file's frontmatter is TypeScript
       between --- fences: a figure there is part of a derivation or of the
       comment explaining one, and neither is a published count. The first
       version scanned the whole file and reported this row's own explanatory
       comment, which names the number it exists to stop being typed. */
    const lines = frontmatterStripped(raw).split('\n');
    lines.forEach((line, i) => {
      for (const m of line.matchAll(HOUSEHOLD_LITERAL)) {
        out.push({ file: rel, line: i + 1, text: m[0] });
      }
    });
  }
  return out;
}

/* R253 [§S5]: the transition envelope, derived rather than typed.
 *
 * One quantity was stated three ways: the page typed "$1.2-$2.0 trillion" in
 * prose and "$1.2T-$2.0T" again in a display tile, `params.ts` carried
 * $1.0-2.2T plus $0.06-0.18T of IT capital, and the cost bridge excluded the
 * whole thing. The page now renders `transitionEnvelope()`. This keeps it
 * that way: a trillion-scale dollar literal written into the rollout page is
 * a fourth copy of a number the parameters already answer.
 *
 * The framework's own controlled envelope is still shown, but it is read from
 * `transitionEnvelope().frameworkLow/High` in params.ts, so there is exactly
 * one place either figure lives. */
export const ENVELOPE_PAGE = 'src/pages/rollout.astro';
export const ENVELOPE_LITERAL_SOURCE = String.raw`\$\d+(?:\.\d+)?\s*(?:T\b|trillion)`;
const ENVELOPE_LITERAL = new RegExp(ENVELOPE_LITERAL_SOURCE, 'g');

export function typedEnvelopeLiterals(root = REPO_ROOT): CodeReference[] {
  const out: CodeReference[] = [];
  const lines = readFileSync(join(root, ENVELOPE_PAGE), 'utf8').split('\n');
  lines.forEach((line, i) => {
    for (const m of line.matchAll(ENVELOPE_LITERAL)) {
      out.push({ file: ENVELOPE_PAGE, line: i + 1, text: m[0] });
    }
  });
  return out;
}

/* R229 [§S3]: the import-time enricher convention, enforced.
 *
 * The convention itself is written at the top of quality.ts, where the
 * pipeline is assembled. This is the half that makes it a rule rather than a
 * comment: every exported `apply*` in src/lib must be declared here with the
 * re-entry flag it guards on, and the flag must actually appear in the
 * function's own module.
 *
 * The failure it prevents: a third enricher mutating the shared catalog at
 * import time with no guard. Nothing would report that, and the symptom is
 * doubled enrichment in whichever consumer imports twice - which in an Astro
 * build is any page that pulls the module through a different graph. */
export const ENRICHERS: Record<string, { module: string; flag: string }> = {
  applyPhaseTargets: { module: 'phase-targets.ts', flag: '__enriched' },
  applyEquationTargets: { module: 'equations.ts', flag: '__equationApplied' }
};

const ENRICHER_EXPORT = /export function (apply\w+)\s*\(/g;

export function undeclaredEnrichers(root = REPO_ROOT): string[] {
  const out: string[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/lib/') || !rel.endsWith('.ts')) continue;
    const text = readFileSync(join(root, rel), 'utf8');
    const module = rel.slice('src/lib/'.length);
    for (const m of text.matchAll(ENRICHER_EXPORT)) {
      const decl = ENRICHERS[m[1]];
      if (!decl) { out.push(m[1] + ' in ' + module + ' is not declared'); continue; }
      if (decl.module !== module) {
        out.push(m[1] + ' is declared in ' + decl.module + ' but defined in ' + module);
      } else if (!text.includes(decl.flag)) {
        out.push(m[1] + ' declares the guard ' + decl.flag + ', which is not in ' + module);
      }
    }
  }
  /* And the reverse: a declared enricher that no longer exists. */
  const defined = new Set<string>();
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/lib/') || !rel.endsWith('.ts')) continue;
    for (const m of readFileSync(join(root, rel), 'utf8').matchAll(ENRICHER_EXPORT)) {
      defined.add(m[1]);
    }
  }
  for (const name of Object.keys(ENRICHERS)) {
    if (!defined.has(name)) out.push(name + ' is declared but no longer exported');
  }
  return out.sort();
}

/* R206 [§S0]: no self-test surface outside the registry.
 *
 * R24 unified the three shapes that existed. This stops a fourth appearing:
 * it scans src/lib for exported self-test functions and reports any whose
 * module is not declared in SELF_TEST_SOURCES. Every orphaned surface in this
 * backlog - R153's two, R230's, R273's - was written, exported and then simply
 * never called, and nothing reported that. */
const SELF_TEST_EXPORT = /export function (selfTest\w*|\w*SelfTests)\s*\(/g;

/* selftests.ts is the registry, not a surface: its own exports (selfTestSummary,
   assertSelfTestsPass) aggregate the others and must not be required to
   register themselves. */
const REGISTRY_MODULE = 'selftests.ts';

const surfaceCache = new Map<string, Array<{ module: string; fn: string }>>();

export function exportedSelfTestSurfaces(root = REPO_ROOT): Array<{ module: string; fn: string }> {
  const hit = surfaceCache.get(root);
  if (hit) return hit;
  const out: Array<{ module: string; fn: string }> = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/lib/') || !rel.endsWith('.ts')) continue;
    if (rel.endsWith('/' + REGISTRY_MODULE)) continue;
    const text = readFileSync(join(root, rel), 'utf8');
    for (const m of text.matchAll(SELF_TEST_EXPORT)) {
      out.push({ module: rel.slice('src/lib/'.length), fn: m[1] });
    }
  }
  surfaceCache.set(root, out);
  return out;
}

export function unregisteredSelfTestSurfaces(
  registeredModules: string[],
  root = REPO_ROOT
): Array<{ module: string; fn: string }> {
  const registered = new Set(registeredModules);
  return exportedSelfTestSurfaces(root).filter((s) => !registered.has(s.module));
}

/* R155 [§S0]: the README's advertised self-test count, read from the file.
 *
 * It said 27. The real figure was 19 (11 model + 1 bridge + 7 tax), and the
 * two orphans R153 wired took it to 21. Fifth instance of a hardcoded count
 * drifting (AB2, AC8, AJ2, AO4). Comparing it against selfTestSummary().total
 * is what stops it being hand-maintained. */
const readmeCache = new Map<string, number | null>();

export function readmeAdvertisedTestCount(root = REPO_ROOT): number | null {
  if (readmeCache.has(root)) return readmeCache.get(root)!;
  const text = readFileSync(join(root, 'README.md'), 'utf8');
  const m = text.match(/(\d+) built-in integrity tests/);
  const n = m ? Number(m[1]) : null;
  readmeCache.set(root, n);
  return n;
}

/* R113 [§S1]: the README's deploy instruction told the reader to set Pages to
 * "Deploy from a branch, folder /docs", which switches Pages off the Actions
 * workflow and publishes the retired tree over the live app at the same URL.
 * The README is also where a new contributor or agent orients, which is why an
 * audit spent seventeen passes reading a directory nothing deploys.
 *
 * The check is three exact patterns rather than a reading of the prose,
 * because prose matching is what let the figure in R155 drift in the first
 * place:
 *   1. does the README name a file inside the retired tree (`docs/<name>`)?
 *   2. does it name `/docs` as a Pages folder?
 *   3. does it name the workflow that actually deploys the site?
 * (1) is the load-bearing half: a README whose file manifest IS the retired
 * tree cannot avoid presenting it as the product. Naming the bare directory in
 * prose is deliberately still allowed, because warning a reader off `docs/` is
 * the correct thing for this file to do - only paths INTO it are the defect.
 * (3) stops the section being deleted rather than corrected. */
const DEPLOY_WORKFLOW = '.github/workflows/deploy.yml';
const PAGES_DEPLOY_ACTION = 'actions/deploy-pages';
const RETIRED_TREE_PATH = /docs\/[A-Za-z0-9_.-]/;
const PAGES_FOLDER_TOKEN = '/docs';

export interface ReadmeDeployDrift {
  retiredPaths: string[]; /* lines naming a file in, or the folder form of, the retired tree */
  missingWorkflowReference: boolean;
}

const deployCache = new Map<string, ReadmeDeployDrift>();

export function readmeDeployDrift(root = REPO_ROOT): ReadmeDeployDrift {
  const hit = deployCache.get(root);
  if (hit) return hit;
  const readme = readFileSync(join(root, 'README.md'), 'utf8');
  const retiredPaths = readme
    .split('\n')
    .map((line, i) => ({ line: line.trim(), n: i + 1 }))
    .filter((x) => RETIRED_TREE_PATH.test(x.line) || x.line.includes(PAGES_FOLDER_TOKEN))
    .map((x) => 'README.md:' + x.n + ': ' + x.line.slice(0, 100));

  /* Only demand the reference when the workflow is what deploys the site. If
     Pages ever legitimately moves off Actions, this half goes quiet instead of
     forcing the README to describe something that no longer runs. */
  let deploysViaActions = false;
  try {
    deploysViaActions = readFileSync(join(root, DEPLOY_WORKFLOW), 'utf8')
      .includes(PAGES_DEPLOY_ACTION);
  } catch {
    deploysViaActions = false;
  }
  const result: ReadmeDeployDrift = {
    retiredPaths: retiredPaths,
    missingWorkflowReference: deploysViaActions && !readme.includes(DEPLOY_WORKFLOW)
  };
  deployCache.set(root, result);
  return result;
}

/* R261 [§S1]: a stated chapter count must be the real one.
 *
 * The app has fourteen chapters. The audit's boundary tables said twelve and
 * omitted Long-Term Care and Risk entirely, so every coverage claim from Pass
 * 18 on used a wrong denominator and four recommendations were scoped against
 * a page set that was missing two of its members. The same figure was stale in
 * three places in specs/HANDOFF.md, which is where a new contributor starts.
 *
 * TABS is the authority (R266), so any prose figure is checkable against it.
 * The number must sit immediately before the noun, which is what keeps
 * sentences like "the other 11 are standalone pages" out of it. */
const STATED_COUNT_DOCS = ['README.md', 'specs/HANDOFF.md'];
const STATED_COUNT = /(\d+)[ -](pages|chapters|tabs)\b/gi;

export interface StatedCountDrift { file: string; line: number; stated: number; text: string }

const statedCache = new Map<string, StatedCountDrift[]>();

export function statedChapterCountDrift(root = REPO_ROOT, tabs = TABS): StatedCountDrift[] {
  const key = root + '|' + tabs.length;
  const hit = statedCache.get(key);
  if (hit) return hit;
  const out: StatedCountDrift[] = [];
  for (const doc of STATED_COUNT_DOCS) {
    let text: string;
    try {
      text = readFileSync(join(root, doc), 'utf8');
    } catch {
      continue; /* a document that does not exist states nothing */
    }
    text.split('\n').forEach((line, i) => {
      for (const m of line.matchAll(STATED_COUNT)) {
        const stated = Number(m[1]);
        if (stated === tabs.length) continue;
        out.push({ file: doc, line: i + 1, stated: stated, text: line.trim().slice(0, 100) });
      }
    });
  }
  statedCache.set(key, out);
  return out;
}

/* R114 [§S1]: no tool may target the retired tree.
 *
 * extract_quality_catalog.py wrote docs/js/qualitydata.js and
 * build_data_phase_targets.py read it and wrote docs/js/dataphases.js, while
 * the live catalog was a hand port marked "do not re-derive". Regenerating
 * updated the retired artifacts and left the deployed site stale, so the
 * reproducibility guarantee the extractor exists to provide never reached the
 * live app. The row's test is "no generator writes to a non-deployed path";
 * this is the checkable form of it, widened to every file under tools/ because
 * a preview server pointed at the retired tree sets the same trap.
 *
 * Path-shaped only: `docs` bounded by a separator or a quote. All four forms
 * are in this repo's history and a narrower pattern misses the one that
 * matters - Python builds the path as ROOT / "docs" / "js", where the
 * separators are operators outside the string and the only boundary is the
 * quote. Prose may still name the retired tree; only pointing at a path in it
 * is the defect. */
const RETIRED_TREE_TARGET =
  /(^|[^A-Za-z0-9_])docs(["'/\\]|$)|["'/\\]docs([^A-Za-z0-9_]|$)/;

export interface ToolTarget { file: string; line: number; text: string }

const toolCache = new Map<string, ToolTarget[]>();

export function retiredTreeTargets(root = REPO_ROOT): ToolTarget[] {
  const hit = toolCache.get(root);
  if (hit) return hit;
  const out: ToolTarget[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('tools/')) continue;
    const lines = readFileSync(join(root, rel), 'utf8').split('\n');
    lines.forEach((line, i) => {
      if (RETIRED_TREE_TARGET.test(line)) {
        out.push({ file: rel, line: i + 1, text: line.trim().slice(0, 100) });
      }
    });
  }
  toolCache.set(root, out);
  return out;
}

/* R112 [§S1]: nothing live may point into the retired tree.
 *
 * R1-R111 all name paths under docs/. The defects they describe are real -
 * §V25 established both engines are faithful ports - but the addresses are
 * wrong, so applying them as written changes nothing a reader sees. Re-targeting
 * the backlog is a document job; the code half of it is this: keep src/ free of
 * any live reference to the retired tree, so a re-targeted address cannot
 * silently drift back.
 *
 * Provenance comments are the point, not the problem. Nearly every module in
 * src/lib says which docs/js file it was ported from, and that history is worth
 * keeping. What must not exist is a docs/ path in executable position: an
 * import specifier, a fetch URL, a string literal. So comments are masked out
 * before the search rather than the whole line being skipped.
 *
 * Masking preserves offsets, so reported line numbers stay true. `//` is only
 * a line comment when it is not preceded by ':', because an .astro template is
 * HTML and a `https://` href would otherwise mask the rest of its own line -
 * which would hide exactly the kind of reference this is looking for.
 *
 * Deliberately not string-aware. Tracking quotes made the scanner wrong on
 * this very file: a regex literal like ["'/\\] reads as an unterminated string,
 * everything after it stays "inside a string", and the comment blocks below
 * stop being recognised. The `:` guard is what string-awareness was for, and
 * `/*` inside a string literal does not occur here. */
const RETIRED_TREE_REFERENCE = /docs\/[A-Za-z0-9_.-]/g;

export interface CodeReference { file: string; line: number; text: string }

/* R21 [§S6a], after review: four source scans had copied the same eight lines -
   walk the tree, keep src/*.ts and *.astro, mask comments, test a global regex
   per line, reset lastIndex, push a CodeReference. The copies drifted in what
   they skipped, which is the part that matters. One scanner, and each caller
   says only what it is looking for and where it is allowed to be. */
export function scanSourceLines(
  pattern: RegExp,
  /* R171 [§S8]: `only` widened from one file to a list. A scan whose scope is
     a named set of narrative surfaces needs to say so as a set; passing them
     one at a time is how the four sites in RESIDUAL_CAVEAT_SITES would end up
     with four callers and three of them forgotten. */
  options: { skip?: string[]; only?: string | string[] } = {},
  root = REPO_ROOT
): CodeReference[] {
  const skip = new Set(options.skip || []);
  const only = options.only === undefined ? null
    : (typeof options.only === 'string' ? [options.only] : options.only);
  const files = only || enumerateSourceFiles(root);
  const out: CodeReference[] = [];
  for (const rel of files) {
    if (!rel.startsWith('src/')) continue;
    if (!rel.endsWith('.ts') && !rel.endsWith('.astro')) continue;
    if (skip.has(rel)) continue;
    const lines = maskComments(readFileSync(join(root, rel), 'utf8')).split('\n');
    lines.forEach((line, i) => {
      if (pattern.test(line)) out.push({ file: rel, line: i + 1, text: line.trim() });
      pattern.lastIndex = 0;
    });
  }
  return out;
}

export function maskComments(text: string): string {
  const out = text.split('');
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    const next = text[i + 1];
    if (c === '/' && next === '*') {
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) {
        if (text[i] !== '\n') out[i] = ' ';
        i += 1;
      }
      out[i] = ' '; out[i + 1] = ' ';
      i += 2;
      continue;
    }
    if (c === '/' && next === '/' && text[i - 1] !== ':') {
      while (i < text.length && text[i] !== '\n') { out[i] = ' '; i += 1; }
      continue;
    }
    if (c === '<' && text.startsWith('<!--', i)) {
      while (i < text.length && !text.startsWith('-->', i)) {
        if (text[i] !== '\n') out[i] = ' ';
        i += 1;
      }
      for (let k = 0; k < 3 && i + k < text.length; k += 1) out[i + k] = ' ';
      i += 3;
      continue;
    }
    i += 1;
  }
  return out.join('');
}

/* R280 [§S15]: a listener bound to a target the guard does not cover.
 *
 * Every client script guards its init with `dataset.wired` on an element
 * inside <main>. <ClientRouter /> replaces that element, so the guard is new
 * on every navigation and the init runs in full each time. That is correct for
 * listeners bound to elements inside <main> - they die with their host - and
 * wrong for anything bound to `document` or `window`, which outlive the swap.
 * fmea-client.ts did the latter and gained one listener per return visit,
 * measured linear, until one click ran selectRecord four times.
 *
 * This is not a defect that stays fixed by being fixed once: it recurs
 * wherever `document` or `window` is reached inside an element-guarded init,
 * and there are seven client scripts. So the shape is checked, not the
 * instance. A registration bound to a global belongs at module scope, which is
 * acronyms-client.ts's pattern (§CB3) and the reason that file is the one to
 * copy.
 *
 * Comments are masked first: a file may describe the hazard, and describing it
 * is the opposite of committing it. */
const GUARD_TOKEN = 'dataset.wired';
const GLOBAL_LISTENER = /\b(document|window)\.addEventListener\b/g;

export interface GuardedGlobalListener { file: string; fn: string; target: string }

/* Brace-match forward from the `{` at or after `from`. Returns the index just
   past the closing brace, or -1 if the source is unbalanced. */
function functionSpanEnd(text: string, from: number): number {
  const open = text.indexOf('{', from);
  if (open < 0) return -1;
  let depth = 0;
  for (let i = open; i < text.length; i += 1) {
    if (text[i] === '{') depth += 1;
    else if (text[i] === '}') {
      depth -= 1;
      if (depth === 0) return i + 1;
    }
  }
  return -1;
}

const guardedListenerCache = new Map<string, GuardedGlobalListener[]>();

export function guardedGlobalListeners(root = REPO_ROOT): GuardedGlobalListener[] {
  const hit = guardedListenerCache.get(root);
  if (hit) return hit;
  const out: GuardedGlobalListener[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/scripts/') || !rel.endsWith('.ts')) continue;
    const masked = maskComments(readFileSync(join(root, rel), 'utf8'));
    const DECL = /\bfunction\s+([A-Za-z0-9_$]+)\s*\([^)]*\)\s*(?::[^{]*)?\{/g;
    let m: RegExpExecArray | null;
    while ((m = DECL.exec(masked)) !== null) {
      const end = functionSpanEnd(masked, m.index);
      if (end < 0) continue;
      const body = masked.slice(m.index, end);
      if (body.indexOf(GUARD_TOKEN) < 0) continue;   // not an element-guarded init
      GLOBAL_LISTENER.lastIndex = 0;
      let g: RegExpExecArray | null;
      while ((g = GLOBAL_LISTENER.exec(body)) !== null) {
        out.push({ file: rel, fn: m[1], target: g[1] });
      }
    }
  }
  guardedListenerCache.set(root, out);
  return out;
}

const codeRefCache = new Map<string, CodeReference[]>();

export function retiredTreeCodeReferences(root = REPO_ROOT): CodeReference[] {
  const hit = codeRefCache.get(root);
  if (hit) return hit;
  const out: CodeReference[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/')) continue;
    const raw = readFileSync(join(root, rel), 'utf8');
    if (!raw.includes('docs/')) continue; /* most files, cheaply skipped */
    const masked = maskComments(raw);
    const lines = raw.split('\n');
    for (const m of masked.matchAll(RETIRED_TREE_REFERENCE)) {
      const line = masked.slice(0, m.index).split('\n').length;
      out.push({ file: rel, line: line, text: lines[line - 1].trim().slice(0, 100) });
    }
  }
  codeRefCache.set(root, out);
  return out;
}

/* R267 [§S0]: route registration.
 *
 * ChapterNav does `TABS.findIndex(...)` and renders nothing on -1, so a page
 * absent from TABS is a dead end at the foot of the chapter with no error.
 * The routes are derived from the manifest rather than typed, so adding a page
 * is enough to trip the check. */
export function pageRoutes(manifest: string[] = FILE_MANIFEST): string[] {
  return manifest
    .filter((p) => p.startsWith('src/pages/') && p.endsWith('.astro'))
    .map((p) => p.slice('src/pages/'.length, -'.astro'.length))
    .filter((name) => !name.startsWith('[')) /* dynamic route, not a fixed path */
    .map((name) => (name === 'index' ? '' : name));
}

export interface RouteDrift {
  unregistered: string[]; /* a page with no TABS entry: navigation dead end */
  unrouted: string[]; /* a TABS entry with no page */
}

export function routeDrift(routes: string[] = pageRoutes(), tabs = TABS): RouteDrift {
  const registered = new Set(tabs.map((t) => t.path));
  const built = new Set(routes);
  return {
    unregistered: routes.filter((r) => !registered.has(r)),
    /* R266 [§S1]: every entry, not only the ones a `ported` flag opted in.
       While that flag existed, a tab added without it was exempt from this
       half of the check and reached the stub route instead - a chapter that
       said "This chapter is being migrated" and shipped. */
    unrouted: tabs
      .filter((t) => t.path !== '')
      .map((t) => t.path)
      .filter((p) => !built.has(p))
  };
}

/* R21 [§S6a]: a numeric literal inside an engine function is a parameter that
 * got away.
 *
 * Ten of them sat in model.ts with no source and no grade, which made their
 * uncertainty zero rather than wide - the Monte Carlo varied everything around
 * them and never them. Sourcing the ten is a one-time fix; this is what stops
 * the eleventh.
 *
 * The span is the engine proper: from the first sampling function to the start
 * of selfTest(), which is test code and holds tolerances, seeds and expected
 * values by the dozen. Comments are masked, so the explanations in that file
 * do not trip it.
 *
 * Every literal in that span must be declared structural in params.ts, with a
 * reason. Model quantities are read from the registry or from a parameter, so
 * after the fix they are not literals at all and cannot appear here. That is
 * why this check does not compare against the registry's VALUES: a registered
 * value typed back into a formula is exactly the duplication the registry
 * exists to remove, so it fails too. */
export const ENGINE_FILE = 'src/lib/model.ts';
/* Review moved this earlier. It used to start at sampleParams, which left the
   ramp and sampling helpers above it unscanned along with the constants block.
   It starts at the first engine function now, so everything that computes is
   inside the span and only the declarations sit above it. */
export const ENGINE_SPAN_START = 'export function rampsAt';
export const ENGINE_SPAN_END = 'export function selfTest';

/* Preceded by neither a word character nor a dot, so `d.pubCost` and
   `p10` are not read as numbers, and property names like `p50:` are skipped
   by the same rule. Exponent forms are matched whole. */
const ENGINE_NUMBER = /(?<![\w.])(\d+\.?\d*(?:e-?\d+)?)/g;

export interface EngineLiteral { line: number; value: number; text: string }

export function engineLiterals(root = REPO_ROOT): EngineLiteral[] {
  const masked = maskComments(readFileSync(join(root, ENGINE_FILE), 'utf8'));
  const lines = masked.split('\n');
  const start = lines.findIndex((l) => l.includes(ENGINE_SPAN_START));
  const end = lines.findIndex((l) => l.includes(ENGINE_SPAN_END));
  if (start < 0 || end < 0 || end <= start) {
    throw new Error('model.ts no longer has an engine span between ' +
      ENGINE_SPAN_START + ' and ' + ENGINE_SPAN_END);
  }
  const out: EngineLiteral[] = [];
  for (let i = start; i < end; i += 1) {
    for (const m of lines[i].matchAll(ENGINE_NUMBER)) {
      out.push({ line: i + 1, value: Number(m[1]), text: lines[i].trim() });
    }
  }
  return out;
}

export function unregisteredEngineLiterals(
  structural: number[],
  root = REPO_ROOT
): EngineLiteral[] {
  const allowed = new Set(structural);
  return engineLiterals(root).filter((l) => !allowed.has(l.value));
}

/* Found by review: the span above starts at the first sampling function, so
   every module-scope declaration ABOVE it was invisible to the check - which is
   exactly where a magic number would go to escape it. Module scope is the
   declared home for a named constant, so declaring one there is right; what was
   missing is that the value has to be declared too.
   The two lists are deliberately different. A quantile of 0.5 is a perfectly
   good band level to declare at module scope and is never a legitimate bare
   number inside an engine formula, where it used to be the OOP share. */
export function undeclaredEngineDeclarations(
  declaration: number[],
  root = REPO_ROOT
): EngineLiteral[] {
  const masked = maskComments(readFileSync(join(root, ENGINE_FILE), 'utf8'));
  const lines = masked.split('\n');
  const spanStart = lines.findIndex((l) => l.includes(ENGINE_SPAN_START));
  const allowed = new Set(declaration);
  const out: EngineLiteral[] = [];
  for (let i = 0; i < spanStart; i += 1) {
    if (/^import|^\s*[A-Za-z_$][\w$]*,?$|from '/.test(lines[i])) continue;
    for (const m of lines[i].matchAll(ENGINE_NUMBER)) {
      const value = Number(m[1]);
      if (!allowed.has(value)) {
        out.push({ line: i + 1, value: value, text: lines[i].trim() });
      }
    }
  }
  return out;
}

/* And the other direction: a constant in the registry that the engine does not
   read is documentation for code that is gone. `usedBy` names the expression,
   which is prose; the identifier is what proves the wiring, so that is what is
   searched for. */
export function unreadEngineConstants(ids: string[], root = REPO_ROOT): string[] {
  const masked = maskComments(readFileSync(join(root, ENGINE_FILE), 'utf8'));
  return ids.filter((id) => !masked.includes("engineConstant('" + id + "')"));
}

/* R60 [§S6b]: a structural knob a scenario can set and the engine never reads
 * is the silent-failure class in its other direction. Same shape as
 * unreadEngineConstants above, and the same reason: a declaration nothing
 * consumes reads as a working control. */
export function unreadStructuralKnobs(names: string[], root = REPO_ROOT): string[] {
  const masked = maskComments(readFileSync(join(root, ENGINE_FILE), 'utf8'));
  /* Review [§S6b]: a bare `includes('s.' + n)` is satisfied by any
     identifier ending in `s`, so `opts.shock` would have passed for
     `s.shock` and renaming the engine's parameter would have broken it
     silently. This file argues elsewhere against checks a deletion cannot
     fail; the same standard applies to its own. The boundary is asserted. */
  return names.filter((n) => !new RegExp('(?<![\\w.])s\\.' + n + '\\b').test(masked));
}

/* R11 [§S6a]: the offset architecture document, held to the engine.
 *
 * A document that describes code is a claim with no test attached, and this one
 * describes the property HANDOFF.md's constraint 4 asks for: that no savings
 * mechanism is counted twice. So it is read, and every mechanism the engine
 * declares has to appear in it. A fifth offset added without a paragraph fails
 * the build, which is the only way a document like this stays true. */
export function mechanismsMissingFromDoc(
  mechanisms: string[],
  doc: string,
  root = REPO_ROOT
): string[] {
  const text = readFileSync(join(root, doc), 'utf8').toLowerCase();
  return mechanisms.filter((m) => !text.includes(m.toLowerCase()));
}

/* R22 [§S6a]: the mature year, computed anywhere but params.ts.
 *
 * Six places derived the same index in three different ways, and they agreed.
 * The failure mode is not that they disagree today, it is that moving END_YEAR
 * moves some of them: the self-tests comparing matureAtScale against the path
 * row would then compare different years and still pass, because each side
 * would be reading its own. So the derivations are what is banned, not the
 * literal - a comment naming 2041 is fine and is masked anyway. */
export const MATURE_YEAR_HOME = 'src/lib/params.ts';
export const MATURE_YEAR_DERIVATION =
  /years\.length\s*-\s*2|END_YEAR\s*-\s*START_YEAR\s*\+\s*1\)\s*-\s*2|204[0-9]\s*-\s*START_YEAR/g;

export function matureYearDerivations(root = REPO_ROOT): CodeReference[] {
  return scanSourceLines(MATURE_YEAR_DERIVATION, { skip: [MATURE_YEAR_HOME] }, root);
}

/* R127 [§S6a]: a primitive type assertion is a claim the compiler stops
 * checking, and X4 is what that costs. `Math.min(v, ins.scaleMax as number)`
 * on an optional field silently produced NaN for a toggle balancer, and the
 * assertion is precisely what suppressed the error that would have caught it -
 * added, by the port, during a migration TO a typed language.
 *
 * Only `as <primitive>` is scanned. Structural casts through `as unknown as`
 * are a different animal: they are how this codebase reaches DOM interfaces
 * that its lib target types loosely, and they assert a shape rather than the
 * presence of a value. Every remaining one is declared below with its reason,
 * so a new assertion has to be argued for rather than typed.
 *
 * Comments are masked, so the paragraph above and the ones in taxmodel.ts do
 * not trip it. */
export const PRIMITIVE_ASSERTION =
  /\bas\s+(number|string|boolean)\b(?!\s*\[)/g;

export interface AllowedAssertion { file: string; why: string }
export const ALLOWED_ASSERTIONS: AllowedAssertion[] = [
  {
    file: 'src/lib/params.ts',
    why: 'BASE2023.investmentResidual is declared 0 and filled by the IIFE ' +
      'below it, so the annotation widens a literal type rather than ' +
      'asserting a value is present.'
  }
];

export function primitiveAssertions(root = REPO_ROOT): CodeReference[] {
  return scanSourceLines(
    PRIMITIVE_ASSERTION, { skip: ALLOWED_ASSERTIONS.map((a) => a.file) }, root);
}

/* R33 [§S6a]: a divergence from a research recommendation is only disclosed if
   a reader can see it, and the only place a reader meets a parameter whole is
   the full parameter table. Declaring the note in params.ts and never
   rendering it would be the same silence in a new place, so the page that
   renders the table is scanned for it. */
export const HEALTH_PAGE = 'src/pages/health.astro';

/* The same file HEALTH_PAGE names, under the name this check reads it by.
   One owner: a second literal path is how two checks end up scanning
   different files after a rename. */
export const PARAMETER_EXPLORER = HEALTH_PAGE;

/* Review: the divergence check tested `note.length >= 80`, which is a check on
   effort rather than on content. A note that does not name the number it
   diverges from is not a disclosure, and that is checkable. */
export function divergenceNamesRecommendation(
  note: string,
  recommended: string
): boolean {
  /* The headline number, not every number in the phrasing: a recommendation
     written as "about 0.39, which is 1 / 2.54" is named by a note that says
     0.39. Requiring all three would fail a note that explains itself in
     percentages, which is what a reader wants. */
  const digits = recommended.match(/[\d.]+/g) || [];
  const headline = digits[0];
  return headline !== undefined && note.includes(headline);
}

/* R141 [§S6b]: the scenario picker is where a reader chooses a stress case, so
 * it is where the case has to say what its numbers rest on. Declaring the
 * provenance in scenarios.ts and never showing it would repeat the omission
 * AP4 filed, one layer further in. */
export const SCENARIO_PICKER = 'src/scripts/health-client.ts';

/* Each read is named separately. The first version of this asked only that
 * SOME `.why` appeared in the file, and it passed with the per-override reason
 * deleted, because the structural block's own `why` satisfied it. A render
 * check that a deletion cannot fail is not a render check. */
export const SCENARIO_PROVENANCE_READS = [
  'ov.why', 'ov.confidence', 'scn.basis', 'scn.structural.why'
];

export function scenarioProvenanceNotRendered(root = REPO_ROOT): string[] {
  const text = readFileSync(join(root, SCENARIO_PICKER), 'utf8');
  return SCENARIO_PROVENANCE_READS.filter((r) => !text.includes(r));
}

/* R139 [§S6b]: the same shape as the divergence check below, and for the same
 * reason. Declaring what low and high mean inside params.ts and never showing
 * it is the silence AP1 filed, moved to a new address. The only place a reader
 * meets a parameter whole is the full parameter table, so that page is read. */
export function bandNoteIsRendered(root = REPO_ROOT): boolean {
  const text = readFileSync(join(root, PARAMETER_EXPLORER), 'utf8');
  return /paramBandNote\(\)/.test(text);
}

/* R237 [§S6b]: and the note about what a slider does to the band, on the page
 * that carries the sliders. */
export function spreadNoteIsRendered(root = REPO_ROOT): boolean {
  const text = readFileSync(join(root, PARAMETER_EXPLORER), 'utf8');
  return /sliderSpreadNote\(\)/.test(text);
}

export function divergenceIsRendered(root = REPO_ROOT): boolean {
  const text = readFileSync(join(root, PARAMETER_EXPLORER), 'utf8');
  return /p\.divergence/.test(text) && /divergence\.note/.test(text) &&
    /divergence\.recommended/.test(text);
}

/* R81 [§S8]: the care cards' section of the Healthcare page must not type a
 * year either. Removing `fromYear` from `CareNha` makes a typed year a type
 * error inside the data, and `careNotesTypingYears` covers the card notes, but
 * the section's own prose is neither: it carried "assuming enactment in 2027",
 * a second copy of the calendar anchor `R256` settled in one place.
 *
 * Scoped to the care section rather than the file, because the rest of the page
 * legitimately publishes calendar years - "2027-2042" is a chart heading and
 * "actual 2023 spending" is a vintage. Comments are masked for the reason
 * `literalRetailTotals` masks them: a note explaining why a year was removed
 * has to name the year. */
export const CARE_SECTION_START = 'id="care-card-section"';

export function careSectionTypedYears(root = REPO_ROOT): string[] {
  const text = maskComments(readFileSync(join(root, HEALTH_PAGE), 'utf8'));
  const from = text.indexOf(CARE_SECTION_START);
  if (from < 0) return ['the care card section is gone: ' + CARE_SECTION_START + ' not found'];
  const end = text.indexOf('</section>', from);
  const section = text.slice(from, end < 0 ? text.length : end);
  return (section.match(/\b20\d\d\b/g) || []);
}

/* R171 [§S8]: the residual-billing caveat has one owner and four render sites,
 * and none of them may restate the figure.
 *
 * §AY3: two requirements govern point-of-care cost and neither promises an
 * absolute zero. The Overview said so; the ten cards, the household
 * calculator's `$0` line and the family-burden sentence did not. Four sites,
 * four separately-typed sentences, one of which was missing.
 *
 * Each site is named separately rather than counted, for the reason
 * DRUG_BASE_READS names its five separately: a check that asks whether SOME
 * site renders the caveat passes with three of the four deleted. */
export const RESIDUAL_CAVEAT_SITES = [
  'src/pages/health.astro',
  'src/pages/index.astro',
  'src/lib/household.ts',
  'src/lib/overview.ts'
];

/* Import statements are stripped before the scan, and that is the whole check.
   The first version tested whether the identifier appeared anywhere in the
   file, and every site imports it - so deleting the render and leaving the
   import behind passed. Proven by the break refusing to fail: exactly the
   read-list defect the §S7 review caught, written again by the pass that had
   read about it. A mention is not a use. */
const IMPORT_STATEMENT = /import\s[\s\S]*?from\s*['"][^'"]*['"];?/g;

export function residualCaveatSitesMissing(root = REPO_ROOT): string[] {
  return RESIDUAL_CAVEAT_SITES.filter((rel) => {
    const text = maskComments(readFileSync(join(root, rel), 'utf8'))
      .replace(IMPORT_STATEMENT, ' ');
    return !/\bRESIDUAL_BILLING_CAVEAT(?![A-Za-z0-9_])/.test(text);
  });
}

/* And the other half of one owner: the figure itself, typed beside a $0 claim,
   is how four sites came to say four things. `care.ts` is the declaration and
   is the only place the number may appear. */
export function typedResidualFigures(root = REPO_ROOT): CodeReference[] {
  return scanSourceLines(
    /\b0\.5\s*%|\bhalf a percent\b/g,
    { skip: ['src/lib/care.ts'], only: RESIDUAL_CAVEAT_SITES },
    root
  );
}

/* R171 [§S8], and the golden rule the §S8 brief inherited: no catalog code in
 * reader prose outside the Data and Quality chapters, whose subject IS the
 * catalog and which explain the codes.
 *
 * `household.ts` rendered "KPP-A3 allows <=0.5% billing exceptions" and
 * `money-flow.ts` labelled a ribbon "(KPP-C8)", both on the Healthcare
 * chapter, both predating §S6a and in no row. R170's own first draft added a
 * third - "Framework requirement SR-DRUG-001" on the insulin card - written by
 * the pass that was fixing the chapter, which is why this exists as a check
 * and not as a sweep.
 *
 * ⚠️ SCOPED, and the scope is the finding. This covers the Healthcare
 * chapter's narrative surfaces only. Measured across all of `src/`, eighteen
 * other files carry catalog codes in string literals; most are legitimate
 * (equations.ts, quality-data.ts, fmea.ts and data-phases.ts ARE the catalog),
 * but `rollout.ts` carries nineteen OI-0xx references, `gov.ts` thirty-three
 * KPP/TPP codes, `hardening.ts` two SR ids and `units-client.ts` one, and
 * whether those reach a reader is a sweep no row owns. Widening this list is
 * how that row gets done.
 *
 * `care.ts` is deliberately NOT in this list. It DECLARES a requirement id and
 * the requirement's verbatim words so the extract check has something to match,
 * and neither reaches a reader; a line scan cannot tell a declared id from a
 * rendered one. Its rendered fields are checked by value instead, in
 * `careProseCatalogCodes`, which is the stronger test of the two. */
export const NARRATIVE_SURFACES = [
  'src/pages/health.astro',
  'src/pages/index.astro',
  'src/lib/household.ts',
  'src/lib/overview.ts',
  'src/lib/money-flow.ts'
];

/* The code shapes the convention names: KPP/TPP/CP metric ids, SR/PR
   requirement ids, OI open issues, SN source notes. Matched only inside string
   literals would need a parser; the whole masked line is enough, because these
   modules have no other reason to write one. */
export const CATALOG_CODE_SOURCE =
  String.raw`\b(?:KPP|TPP|CP|SR|PR|OI|SN|GAP)-[A-Z0-9][A-Z0-9.\-]*`;

export function narrativeCatalogCodes(root = REPO_ROOT): CodeReference[] {
  return scanSourceLines(
    new RegExp(CATALOG_CODE_SOURCE, 'g'), { only: NARRATIVE_SURFACES }, root);
}

/* R85 [§S8]: the client has to actually re-derive the card years.
 *
 * `careYearShiftDrift` proves the MODEL moves the years under four scenarios.
 * It says nothing about whether the page shows the move, and the defect §AG7
 * filed is precisely a model that moves while the cards do not. Deleting one
 * call from health-client.ts would restore that state with every self-test
 * still green.
 *
 * Each of the four sentence builders is named separately, for the reason
 * SCENARIO_PROVENANCE_READS gives and the reason the §S7 review found the hard
 * way: a check that asks whether SOME care function is called passes with three
 * of the four deleted. The call parenthesis is required, so an import that is
 * no longer used does not satisfy it. */
export const HEALTH_CLIENT = 'src/scripts/health-client.ts';

export const CARE_SCENARIO_CALLS = [
  'careChipText', 'carePhasingText', 'careEarlyText', 'careRequirementText',
  'buildRamps', 'scenarioStructural'
];

export function careScenarioCallsMissing(root = REPO_ROOT): string[] {
  const text = maskComments(readFileSync(join(root, HEALTH_CLIENT), 'utf8'));
  return CARE_SCENARIO_CALLS.filter(
    (name) => !new RegExp('\\b' + name + '\\s*\\(').test(text));
}

/* R170 [§S8]: a framework requirement a card quotes has to be in the framework.
 *
 * §AG2's complaint about the therapy card was that its cited source does not
 * contain the figures it is cited for. The same test applied to a requirement:
 * the id has to exist in the extract and the card's words have to be that
 * requirement's words, not a paraphrase that drifted. Whitespace is collapsed
 * because the card wraps its quote across source lines and the extract does not. */
export const FRAMEWORK_EXTRACT = 'research/framework_v2_extract.md';

function collapse(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

export function careRequirementsNotInFramework(root = REPO_ROOT): string[] {
  const text = collapse(readFileSync(join(root, FRAMEWORK_EXTRACT), 'utf8'));
  const out: string[] = [];
  for (const card of CARE_SCENARIOS) {
    const f = card.nha.framework;
    if (!f) continue;
    if (!text.includes(f.id)) { out.push(card.id + ': ' + f.id + ' is not in the extract'); continue; }
    if (!text.includes(collapse(f.quote))) {
      out.push(card.id + ': ' + f.id + ' does not read the way the card quotes it');
    }
  }
  return out;
}

/* R296 [§S7]: the medications chapter is where the drug base meets a reader,
 * so it is where the base has to be the model's own decomposition rather than
 * a number typed beside it. BY2 found the spend bar captioned "Modeled
 * all-drug spending split" with its 65% segment labelled with the CMS retail
 * figure, which is $5.2B away from the model's retail component: close enough
 * that nobody would notice, far enough to be the $16.9B reconciliation failure
 * in miniature.
 *
 * Each read is named separately, for the reason SCENARIO_PROVENANCE_READS
 * gives: a check that only asks whether SOME field is read passes with the
 * deletion it exists to catch. */
export const MEDICATIONS_PAGE = 'src/pages/medications.astro';

export const DRUG_BASE_READS = [
  'DRUG_BASE_LABELS.retail', 'DRUG_BASE_LABELS.nonRetail',
  'DRUG_BASE_LABELS.total', 'DRUG_BASE_LABELS.retailWidth',
  'DRUG_BASE_LABELS.nonRetailWidth'
];

/* Code review [§S7]: `includes` was the wrong test, and it defeated the reason
 * these five are named separately. `DRUG_BASE.retail` is a substring of
 * `DRUG_BASE.retailPct`, and `DRUG_BASE.nonRetail` of `DRUG_BASE.nonRetailPct`,
 * so a page that read only the two percentages satisfied all five entries: the
 * two label reads this check exists to protect could be deleted and it still
 * passed. Exactly the failure the comment above claims to avoid, one layer in.
 * The property name has to end where the entry ends. */
function readsField(text: string, read: string): boolean {
  return new RegExp(read.replace('.', '\\.') + '(?![A-Za-z0-9_])').test(text);
}

export function drugBaseNotRendered(root = REPO_ROOT): string[] {
  const text = readFileSync(join(root, MEDICATIONS_PAGE), 'utf8');
  return DRUG_BASE_READS.filter((r) => !readsField(text, r));
}

/* Code review [§S7]: comments are masked, for the reason
 * retiredTreeCodeReferences masks them: a provenance comment explaining why a
 * figure was removed necessarily quotes the figure, and quoting it in a
 * comment is not publishing it. The first version of this scan failed on its
 * own fix note. */

/* R214 [§S7]: and the other half of one owner. A hand-typed dollar total in
 * the retail drug band is how the CMS 2024 figure got onto a segment the model
 * produced in the first place. The band is deliberately narrow: it covers the
 * retail prescription drug line and nothing else the chapter publishes. A
 * derived read reaches the page as `${...}B`, which starts with a brace and
 * cannot match. */
export const RETAIL_BAND_LOW = 400;
export const RETAIL_BAND_HIGH = 560;

/* R173 + R204 [§S7]: and the note that says the base is modal and dated has to
 * reach the page, for the reason bandNoteIsRendered exists: declaring it in the
 * module and never showing it is the omission, moved one layer in. */
export function drugBaseNoteIsRendered(root = REPO_ROOT): boolean {
  const text = readFileSync(join(root, MEDICATIONS_PAGE), 'utf8');
  return /drugBaseNote\(\)/.test(text);
}

/* R50 [§S7]: and the note saying the two reduction controls are separate has
 * to sit beside the control it is about. §BY5's point was that the caption is
 * where the reader forms the belief. */
export function drugLeverNoteIsRendered(root = REPO_ROOT): boolean {
  const text = readFileSync(join(root, MEDICATIONS_PAGE), 'utf8');
  return /drugLeverNote\(\)/.test(text);
}

/* R176 [§S7]: the six inclusion reasons are typed in the data and typed again,
 * as strings, into the tab's filter markup. A union that the filter does not
 * offer is a reason no reader can select; a filter option outside the union
 * matches nothing and silently returns an empty list, which is the failure
 * mode the union was added to stop. Read the option values and hold the two
 * lists equal in both directions. */
export function medicationsFilterReasons(root = REPO_ROOT): string[] {
  const text = readFileSync(join(root, MEDICATIONS_PAGE), 'utf8');
  const block = text.match(
    /<select id="medications-reason-filter">([\s\S]*?)<\/select>/);
  if (!block) return [];
  const out: string[] = [];
  for (const m of block[1].matchAll(/<option value="([^"]*)"/g)) {
    if (m[1]) out.push(m[1]);
  }
  return out;
}

/* R175 [§S7]: and the principle behind the phases has to be on the page that
 * publishes them, not only in the module that derives them. */
export function phasePrincipleIsRendered(root = REPO_ROOT): boolean {
  const text = readFileSync(join(root, MEDICATIONS_PAGE), 'utf8');
  return /phasePrinciple\(\)/.test(text);
}

/* R34 [§S7]: the IRA scores are correct as original scores and overstated as
 * current standing, and they appear in four places that did not agree about
 * that. `research/03` graded them High-for-original and Medium-for-durability
 * and named the 2025 re-scoring; `research/01` graded the identical figures
 * HIGH and called them the most authoritative data point in the section with
 * no re-scoring caveat at all; the seed CSV carried `high` with a note that
 * said the same; BUILD-BRIEF repeated the claim.
 *
 * Rather than declare the four sites, the scan finds them: a file that states
 * the $98.5B score in an IRA context has to carry the caveat. A new site
 * quoting the figure is caught without anyone remembering to add it to a list.
 * The IRA token is what keeps `fmea.ts`, which uses 98.5 as a headroom
 * percentage, out of the sweep. */
export const IRA_SCORE = /\$?98\.5\b/g;
export const IRA_CONTEXT = /\bIRA\b|Inflation Reduction Act/;
export const IRA_RESCORING = /re-scor|rescor|revised .{0,40}downward|downward .{0,40}re-?scor/i;

/* The caveat has to sit with the figure, not merely somewhere in the same
 * file. The first version of this asked whether the file contained the token
 * anywhere, and the break written to prove it could not fail: research/01's
 * new text mentions "re-scoring" a second time while explaining the history,
 * so deleting the caveat from the confidence line left the check passing. A
 * window is what makes the check about the quotation rather than the document.
 * 1200 characters covers the value line to the confidence line in the research
 * entries, which is the longest gap any of the four sites has.
 *
 * The window reads both ways. A first attempt read only forward and called a
 * caveat written immediately BEFORE the figure missing, which is the wrong
 * answer: a reader meets it either way round. */
export const IRA_CAVEAT_WINDOW = 1200;

const IRA_SCAN_DIRS = ['research', 'src/lib'];
const IRA_SCAN_FILES = ['BUILD-BRIEF.md'];

function iraScanFiles(root: string): string[] {
  const files: string[] = [...IRA_SCAN_FILES];
  for (const dir of IRA_SCAN_DIRS) {
    for (const name of readdirSync(join(root, dir))) {
      if (/\.(md|csv|ts)$/.test(name)) files.push(dir + '/' + name);
    }
  }
  return files;
}

/* Every place the score is quoted, with the offset, so a file quoting it three
 * times has to caveat all three. */
function iraQuotations(root: string, rel: string): number[] {
  const text = readFileSync(join(root, rel), 'utf8');
  if (!IRA_CONTEXT.test(text)) return [];
  const at: number[] = [];
  for (const m of text.matchAll(IRA_SCORE)) at.push(m.index ?? 0);
  return at;
}

export function iraScoresWithoutCaveat(root = REPO_ROOT): string[] {
  const bad: string[] = [];
  for (const rel of iraScanFiles(root)) {
    const at = iraQuotations(root, rel);
    if (!at.length) continue;
    const text = readFileSync(join(root, rel), 'utf8');
    for (const i of at) {
      const window = text.slice(Math.max(0, i - IRA_CAVEAT_WINDOW),
        i + IRA_CAVEAT_WINDOW);
      if (!IRA_RESCORING.test(window)) bad.push(rel + '@' + i);
    }
  }
  return bad;
}

/* The quotations that do carry it, so the check reports a number rather than
 * only an absence, and a scan that silently stops matching anything is
 * visible. */
export function iraScoreSites(root = REPO_ROOT): string[] {
  const out: string[] = [];
  for (const rel of iraScanFiles(root)) {
    for (const i of iraQuotations(root, rel)) out.push(rel + '@' + i);
  }
  return out;
}

/* R52 [§S7]: the medication tests asserted that multiplication works. What
 * they should assert is what the page and the model have agreed to share, and
 * that needs the page's actual controls rather than numbers retyped into a
 * test. Both readers below fail closed: a control that stops being a range
 * input, or a boundary sentence that stops stating two figures, returns null
 * and the assertion has nothing to pass on. */
export function medicationsSliderRange(
  id: string, root = REPO_ROOT
): { min: number; max: number; value: number } | null {
  const text = readFileSync(join(root, MEDICATIONS_PAGE), 'utf8');
  const m = text.match(new RegExp(
    '<input id="' + id + '" type="range" min="(\\d+)" max="(\\d+)"[^>]*value="(\\d+)"'));
  return m ? { min: Number(m[1]), max: Number(m[2]), value: Number(m[3]) } : null;
}

/* The stated stress boundary, read out of the prose §BY4 verified and §S7
 * protects. Read, not rewritten: the disclosure is do-not-touch, so this
 * checks it rather than deriving it. */
export function statedStressBoundary(root = REPO_ROOT): [number, number] | null {
  const text = readFileSync(join(root, MEDICATIONS_PAGE), 'utf8');
  const m = text.match(/stress boundary is\s+approximately \$(\d+)[^\d]+(\d+)B per year/);
  return m ? [Number(m[1]), Number(m[2])] : null;
}

export function literalRetailTotals(root = REPO_ROOT): string[] {
  const text = maskComments(readFileSync(join(root, MEDICATIONS_PAGE), 'utf8'));
  const found: string[] = [];
  for (const m of text.matchAll(/\$(\d{3}(?:\.\d)?)B/g)) {
    const v = Number(m[1]);
    if (v >= RETAIL_BAND_LOW && v <= RETAIL_BAND_HIGH) found.push(m[0]);
  }
  return found;
}
