/* R271 [§S0]: compare the committed file manifest against the working tree.
 *
 * The audit that produced this backlog could not enumerate a directory: the
 * git trees API, the Contents API and the HTML tree view all returned empty,
 * so its only discovery mechanism was seeing a file named inside another file.
 * That mechanism missed two entire public chapters (ltc, risk), the route
 * registry that enumerates every chapter (tabs.ts), and 23 files that are named
 * in neither audit document.
 *
 * Build-time only. Imported by selftests.ts, which runs in Node during
 * `astro build` and under vitest; nothing in src/scripts/ imports it, so
 * node:fs never reaches a client bundle.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FILE_MANIFEST } from './file-manifest';
import { TABS } from './tabs';

/* src/lib/manifest-check.ts -> repo root */
const REPO_ROOT = fileURLToPath(new URL('../..', import.meta.url));

export const MANIFEST_ROOTS = ['src', 'tools', 'research'];

/* Not source, and regenerated by anyone who runs a tools/*.py generator, so
   listing it would make the manifest drift on every run. Mirrors .gitignore. */
const IGNORED_DIRS = new Set(['__pycache__']);

/* Memoised per root. These run inside self-tests, which vitest re-imports once
   per test file; without the cache the suite spends minutes re-walking the tree
   and re-reading a 119 KB catalog. */
const fileCache = new Map<string, string[]>();

export function enumerateSourceFiles(root = REPO_ROOT): string[] {
  const hit = fileCache.get(root);
  if (hit) return hit;
  const out: string[] = [];
  for (const dir of MANIFEST_ROOTS) walk(join(root, dir), root, out);
  out.sort();
  fileCache.set(root, out);
  return out;
}

function walk(dir: string, root: string, out: string[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return; /* a root that does not exist is reported as drift, not a crash */
  }
  for (const name of entries) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      if (!IGNORED_DIRS.has(name)) walk(full, root, out);
    }
    else out.push(relative(root, full).split(sep).join('/'));
  }
}

export interface ManifestDrift {
  unlisted: string[]; /* on disk, absent from the manifest */
  missing: string[]; /* in the manifest, absent from disk */
}

export function manifestDrift(actual: string[] = enumerateSourceFiles()): ManifestDrift {
  const listed = new Set(FILE_MANIFEST);
  const onDisk = new Set(actual);
  return {
    unlisted: actual.filter((p) => !listed.has(p)),
    missing: FILE_MANIFEST.filter((p) => !onDisk.has(p))
  };
}

/* R206 [§S0]: no self-test surface outside the registry.
 *
 * R24 unified the three shapes that existed. This stops a fourth appearing:
 * it scans src/lib for exported self-test functions and reports any whose
 * module is not declared in SELF_TEST_SOURCES. Every orphaned surface in this
 * backlog - R153's two, R230's, R273's - was written, exported and then simply
 * never called, and nothing reported that. */
const SELF_TEST_EXPORT = /export function (selfTest\w*|\w*SelfTests)\s*\(/g;

/* selftests.ts is the registry, not a surface: its own exports (selfTestSummary,
   assertSelfTestsPass) aggregate the others and must not be required to
   register themselves. */
const REGISTRY_MODULE = 'selftests.ts';

const surfaceCache = new Map<string, Array<{ module: string; fn: string }>>();

export function exportedSelfTestSurfaces(root = REPO_ROOT): Array<{ module: string; fn: string }> {
  const hit = surfaceCache.get(root);
  if (hit) return hit;
  const out: Array<{ module: string; fn: string }> = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/lib/') || !rel.endsWith('.ts')) continue;
    if (rel.endsWith('/' + REGISTRY_MODULE)) continue;
    const text = readFileSync(join(root, rel), 'utf8');
    for (const m of text.matchAll(SELF_TEST_EXPORT)) {
      out.push({ module: rel.slice('src/lib/'.length), fn: m[1] });
    }
  }
  surfaceCache.set(root, out);
  return out;
}

export function unregisteredSelfTestSurfaces(
  registeredModules: string[],
  root = REPO_ROOT
): Array<{ module: string; fn: string }> {
  const registered = new Set(registeredModules);
  return exportedSelfTestSurfaces(root).filter((s) => !registered.has(s.module));
}

/* R155 [§S0]: the README's advertised self-test count, read from the file.
 *
 * It said 27. The real figure was 19 (11 model + 1 bridge + 7 tax), and the
 * two orphans R153 wired took it to 21. Fifth instance of a hardcoded count
 * drifting (AB2, AC8, AJ2, AO4). Comparing it against selfTestSummary().total
 * is what stops it being hand-maintained. */
const readmeCache = new Map<string, number | null>();

export function readmeAdvertisedTestCount(root = REPO_ROOT): number | null {
  if (readmeCache.has(root)) return readmeCache.get(root)!;
  const text = readFileSync(join(root, 'README.md'), 'utf8');
  const m = text.match(/(\d+) built-in integrity tests/);
  const n = m ? Number(m[1]) : null;
  readmeCache.set(root, n);
  return n;
}

/* R113 [§S1]: the README's deploy instruction told the reader to set Pages to
 * "Deploy from a branch, folder /docs", which switches Pages off the Actions
 * workflow and publishes the retired tree over the live app at the same URL.
 * The README is also where a new contributor or agent orients, which is why an
 * audit spent seventeen passes reading a directory nothing deploys.
 *
 * The check is three exact patterns rather than a reading of the prose,
 * because prose matching is what let the figure in R155 drift in the first
 * place:
 *   1. does the README name a file inside the retired tree (`docs/<name>`)?
 *   2. does it name `/docs` as a Pages folder?
 *   3. does it name the workflow that actually deploys the site?
 * (1) is the load-bearing half: a README whose file manifest IS the retired
 * tree cannot avoid presenting it as the product. Naming the bare directory in
 * prose is deliberately still allowed, because warning a reader off `docs/` is
 * the correct thing for this file to do - only paths INTO it are the defect.
 * (3) stops the section being deleted rather than corrected. */
const DEPLOY_WORKFLOW = '.github/workflows/deploy.yml';
const PAGES_DEPLOY_ACTION = 'actions/deploy-pages';
const RETIRED_TREE_PATH = /docs\/[A-Za-z0-9_.-]/;
const PAGES_FOLDER_TOKEN = '/docs';

export interface ReadmeDeployDrift {
  retiredPaths: string[]; /* lines naming a file in, or the folder form of, the retired tree */
  missingWorkflowReference: boolean;
}

const deployCache = new Map<string, ReadmeDeployDrift>();

export function readmeDeployDrift(root = REPO_ROOT): ReadmeDeployDrift {
  const hit = deployCache.get(root);
  if (hit) return hit;
  const readme = readFileSync(join(root, 'README.md'), 'utf8');
  const retiredPaths = readme
    .split('\n')
    .map((line, i) => ({ line: line.trim(), n: i + 1 }))
    .filter((x) => RETIRED_TREE_PATH.test(x.line) || x.line.includes(PAGES_FOLDER_TOKEN))
    .map((x) => 'README.md:' + x.n + ': ' + x.line.slice(0, 100));

  /* Only demand the reference when the workflow is what deploys the site. If
     Pages ever legitimately moves off Actions, this half goes quiet instead of
     forcing the README to describe something that no longer runs. */
  let deploysViaActions = false;
  try {
    deploysViaActions = readFileSync(join(root, DEPLOY_WORKFLOW), 'utf8')
      .includes(PAGES_DEPLOY_ACTION);
  } catch {
    deploysViaActions = false;
  }
  const result: ReadmeDeployDrift = {
    retiredPaths: retiredPaths,
    missingWorkflowReference: deploysViaActions && !readme.includes(DEPLOY_WORKFLOW)
  };
  deployCache.set(root, result);
  return result;
}

/* R261 [§S1]: a stated chapter count must be the real one.
 *
 * The app has fourteen chapters. The audit's boundary tables said twelve and
 * omitted Long-Term Care and Risk entirely, so every coverage claim from Pass
 * 18 on used a wrong denominator and four recommendations were scoped against
 * a page set that was missing two of its members. The same figure was stale in
 * three places in specs/HANDOFF.md, which is where a new contributor starts.
 *
 * TABS is the authority (R266), so any prose figure is checkable against it.
 * The number must sit immediately before the noun, which is what keeps
 * sentences like "the other 11 are standalone pages" out of it. */
const STATED_COUNT_DOCS = ['README.md', 'specs/HANDOFF.md'];
const STATED_COUNT = /(\d+)[ -](pages|chapters|tabs)\b/gi;

export interface StatedCountDrift { file: string; line: number; stated: number; text: string }

const statedCache = new Map<string, StatedCountDrift[]>();

export function statedChapterCountDrift(root = REPO_ROOT, tabs = TABS): StatedCountDrift[] {
  const key = root + '|' + tabs.length;
  const hit = statedCache.get(key);
  if (hit) return hit;
  const out: StatedCountDrift[] = [];
  for (const doc of STATED_COUNT_DOCS) {
    let text: string;
    try {
      text = readFileSync(join(root, doc), 'utf8');
    } catch {
      continue; /* a document that does not exist states nothing */
    }
    text.split('\n').forEach((line, i) => {
      for (const m of line.matchAll(STATED_COUNT)) {
        const stated = Number(m[1]);
        if (stated === tabs.length) continue;
        out.push({ file: doc, line: i + 1, stated: stated, text: line.trim().slice(0, 100) });
      }
    });
  }
  statedCache.set(key, out);
  return out;
}

/* R114 [§S1]: no tool may target the retired tree.
 *
 * extract_quality_catalog.py wrote docs/js/qualitydata.js and
 * build_data_phase_targets.py read it and wrote docs/js/dataphases.js, while
 * the live catalog was a hand port marked "do not re-derive". Regenerating
 * updated the retired artifacts and left the deployed site stale, so the
 * reproducibility guarantee the extractor exists to provide never reached the
 * live app. The row's test is "no generator writes to a non-deployed path";
 * this is the checkable form of it, widened to every file under tools/ because
 * a preview server pointed at the retired tree sets the same trap.
 *
 * Path-shaped only: `docs` bounded by a separator or a quote. All four forms
 * are in this repo's history and a narrower pattern misses the one that
 * matters - Python builds the path as ROOT / "docs" / "js", where the
 * separators are operators outside the string and the only boundary is the
 * quote. Prose may still name the retired tree; only pointing at a path in it
 * is the defect. */
const RETIRED_TREE_TARGET =
  /(^|[^A-Za-z0-9_])docs(["'/\\]|$)|["'/\\]docs([^A-Za-z0-9_]|$)/;

export interface ToolTarget { file: string; line: number; text: string }

const toolCache = new Map<string, ToolTarget[]>();

export function retiredTreeTargets(root = REPO_ROOT): ToolTarget[] {
  const hit = toolCache.get(root);
  if (hit) return hit;
  const out: ToolTarget[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('tools/')) continue;
    const lines = readFileSync(join(root, rel), 'utf8').split('\n');
    lines.forEach((line, i) => {
      if (RETIRED_TREE_TARGET.test(line)) {
        out.push({ file: rel, line: i + 1, text: line.trim().slice(0, 100) });
      }
    });
  }
  toolCache.set(root, out);
  return out;
}

/* R112 [§S1]: nothing live may point into the retired tree.
 *
 * R1-R111 all name paths under docs/. The defects they describe are real -
 * §V25 established both engines are faithful ports - but the addresses are
 * wrong, so applying them as written changes nothing a reader sees. Re-targeting
 * the backlog is a document job; the code half of it is this: keep src/ free of
 * any live reference to the retired tree, so a re-targeted address cannot
 * silently drift back.
 *
 * Provenance comments are the point, not the problem. Nearly every module in
 * src/lib says which docs/js file it was ported from, and that history is worth
 * keeping. What must not exist is a docs/ path in executable position: an
 * import specifier, a fetch URL, a string literal. So comments are masked out
 * before the search rather than the whole line being skipped.
 *
 * Masking preserves offsets, so reported line numbers stay true. `//` is only
 * a line comment when it is not preceded by ':', because an .astro template is
 * HTML and a `https://` href would otherwise mask the rest of its own line -
 * which would hide exactly the kind of reference this is looking for.
 *
 * Deliberately not string-aware. Tracking quotes made the scanner wrong on
 * this very file: a regex literal like ["'/\\] reads as an unterminated string,
 * everything after it stays "inside a string", and the comment blocks below
 * stop being recognised. The `:` guard is what string-awareness was for, and
 * `/*` inside a string literal does not occur here. */
const RETIRED_TREE_REFERENCE = /docs\/[A-Za-z0-9_.-]/g;

export interface CodeReference { file: string; line: number; text: string }

export function maskComments(text: string): string {
  const out = text.split('');
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    const next = text[i + 1];
    if (c === '/' && next === '*') {
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) {
        if (text[i] !== '\n') out[i] = ' ';
        i += 1;
      }
      out[i] = ' '; out[i + 1] = ' ';
      i += 2;
      continue;
    }
    if (c === '/' && next === '/' && text[i - 1] !== ':') {
      while (i < text.length && text[i] !== '\n') { out[i] = ' '; i += 1; }
      continue;
    }
    if (c === '<' && text.startsWith('<!--', i)) {
      while (i < text.length && !text.startsWith('-->', i)) {
        if (text[i] !== '\n') out[i] = ' ';
        i += 1;
      }
      for (let k = 0; k < 3 && i + k < text.length; k += 1) out[i + k] = ' ';
      i += 3;
      continue;
    }
    i += 1;
  }
  return out.join('');
}

const codeRefCache = new Map<string, CodeReference[]>();

export function retiredTreeCodeReferences(root = REPO_ROOT): CodeReference[] {
  const hit = codeRefCache.get(root);
  if (hit) return hit;
  const out: CodeReference[] = [];
  for (const rel of enumerateSourceFiles(root)) {
    if (!rel.startsWith('src/')) continue;
    const raw = readFileSync(join(root, rel), 'utf8');
    if (!raw.includes('docs/')) continue; /* most files, cheaply skipped */
    const masked = maskComments(raw);
    const lines = raw.split('\n');
    for (const m of masked.matchAll(RETIRED_TREE_REFERENCE)) {
      const line = masked.slice(0, m.index).split('\n').length;
      out.push({ file: rel, line: line, text: lines[line - 1].trim().slice(0, 100) });
    }
  }
  codeRefCache.set(root, out);
  return out;
}

/* R267 [§S0]: route registration.
 *
 * ChapterNav does `TABS.findIndex(...)` and renders nothing on -1, so a page
 * absent from TABS is a dead end at the foot of the chapter with no error.
 * The routes are derived from the manifest rather than typed, so adding a page
 * is enough to trip the check. */
export function pageRoutes(manifest: string[] = FILE_MANIFEST): string[] {
  return manifest
    .filter((p) => p.startsWith('src/pages/') && p.endsWith('.astro'))
    .map((p) => p.slice('src/pages/'.length, -'.astro'.length))
    .filter((name) => !name.startsWith('[')) /* dynamic route, not a fixed path */
    .map((name) => (name === 'index' ? '' : name));
}

export interface RouteDrift {
  unregistered: string[]; /* a page with no TABS entry: navigation dead end */
  unrouted: string[]; /* a TABS entry with no page */
}

export function routeDrift(routes: string[] = pageRoutes(), tabs = TABS): RouteDrift {
  const registered = new Set(tabs.map((t) => t.path));
  const built = new Set(routes);
  return {
    unregistered: routes.filter((r) => !registered.has(r)),
    /* R266 [§S1]: every entry, not only the ones a `ported` flag opted in.
       While that flag existed, a tab added without it was exempt from this
       half of the check and reached the stub route instead - a chapter that
       said "This chapter is being migrated" and shipped. */
    unrouted: tabs
      .filter((t) => t.path !== '')
      .map((t) => t.path)
      .filter((p) => !built.has(p))
  };
}
