/* R271 [§S0]: regenerate src/lib/file-manifest.ts from the working tree.
 *
 * Run after adding or removing a file under src/, tools/ or research/:
 *
 *     node tools/build_file_manifest.mjs
 *
 * The build gate in astro.config.mjs fails when the committed manifest and the
 * working tree disagree, so an unlisted file cannot ship unnoticed. That is the
 * point: the audit's inventory was a guess for 61 passes because nothing could
 * list a directory.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ROOTS = ['src', 'tools', 'research'];
/* Must match IGNORED_DIRS in src/lib/manifest-check.ts, or the two walks
   disagree and the gate fails on a directory neither side wants listed. */
const IGNORED_DIRS = new Set(['__pycache__']);
const OUT = join(ROOT, 'src', 'lib', 'file-manifest.ts');

function walk(dir, out) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      if (!IGNORED_DIRS.has(name)) walk(full, out);
    } else out.push(relative(ROOT, full).split(sep).join('/'));
  }
}

const files = [];
for (const dir of ROOTS) walk(join(ROOT, dir), files);
files.sort();

const body = files.map((f) => `  '${f}'`).join(',\n');
writeFileSync(
  OUT,
  `/* GENERATED by tools/build_file_manifest.mjs - do not edit by hand.
 *
 * R271 [§S0]: the committed inventory of every file under src/, tools/ and
 * research/. The build gate compares this against the working tree, so adding
 * a file without listing it fails astro build.
 *
 * Regenerate with:  node tools/build_file_manifest.mjs
 */
export const FILE_MANIFEST: string[] = [
${body}
];
`,
  'utf8'
);
console.log(`file-manifest.ts: ${files.length} files`);
