"""Extract the controlled quality and cost parameter catalogs for the dashboard.

The framework DOCX is the controlled, machine-readable companion to the
published PDF.  This script keeps the dashboard catalog reproducible instead
of maintaining hundreds of records by hand.

R114 [S1]: it used to write the catalog into the retired tree, which nothing
deploys, while the live catalog was a hand port marked "do not re-derive."
The reproducibility guarantee this script exists to provide never reached the
deployed site, and any change to the controlled DOCX needed a manual re-port
that nothing verified.  It now writes src/lib/quality-data.ts directly.

Two things stand between the DOCX and the live file, and both are declared
here rather than applied by hand afterwards:

  * HOUSE_STYLE - the published dashboard uses no em dashes, so the DOCX's
    "name — definition" and "input/derived—resolve" forms are rewritten.
  * WORDING - two CP-TOT records say "system" where the DOCX says
    "framework", because the dashboard describes the system being modelled
    rather than the document describing it.

The DOCX yields 430 records.  The live catalog declares 440: ten merit
health-talent immigration KPP/TPP added by hand in 2026-08 that are not in
the DOCX.  They are carried in tools/quality_catalog_addendum.json and
appended, so the file regenerates exactly.  Sourcing or quarantining those
ten is R115, not this script's job.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from docx import Document


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "National_Health_Assurance_Framework_v2.0.0_FINAL.docx"
ADDENDUM = Path(__file__).resolve().parent / "quality_catalog_addendum.json"
OUTPUT = ROOT / "src" / "lib" / "quality-data.ts"

# Applied to every extracted record.  Keyed by field, then by the DOCX form.
HOUSE_STYLE = {
    "calculation": (" — ", ": "),
    "modelRole": ("—", ", "),
}

# Deliberate departures from the DOCX wording, by record and field.
WORDING = {
    ("CP-TOT-009", "name"): ("framework", "system"),
    ("CP-TOT-009", "calculation"): ("framework", "system"),
    ("CP-TOT-010", "name"): ("framework", "system"),
    ("CP-TOT-010", "calculation"): ("framework", "system"),
}

# The TypeScript around the payload.  The declared interfaces are the live
# file's contract with the rest of src/, so they are emitted, not re-derived.
TS_HEADER = '''/* Quality catalog base data. GENERATED by tools/extract_quality_catalog.py
   from National_Health_Assurance_Framework_v2.0.0_FINAL.docx (430 records)
   plus tools/quality_catalog_addendum.json (10 merit health-talent
   immigration KPP/TPP added 2026-08, not in the DOCX) = 440 parameters
   (45 KPP + 85 TPP + 310 CP), with phases, gates, concepts, and counts.

   Regenerate with:  python tools/extract_quality_catalog.py
   Do not edit the payload by hand: the next regeneration discards the edit.
   phase-targets.ts augments each parameter.rollout with derived interim
   targets.

   A gate's progression floor is written to every phase its decision point
   names (GATE_PHASES in the generator). Gate 1's names a transition, so its
   claims floor is carried at both P3 and P4; the other four name an event and
   carry one phase each. Each floor keeps the gate that produced it. */

/* `raw` and `bounded` are written by equations.ts, not by this generator
   (R232): when a computed value is clamped to a committed floor or milestone,
   `value` holds the number the reader is shown and `raw` holds the number the
   equation produced, so the two can be displayed together. */
export interface RolloutEntry { phase: string; value: string; kind: string; gate?: string; basis?: string; justification?: string; interpretation?: string; raw?: string; bounded?: boolean; }
export interface QualityParameter {
  id: string; type: string; name: string; concept: string; where: string; target: string;
  calculation: string; datasets: string; ownerVerifier: string; status: string; unit: string;
  modelRole: string; temporal: string; unitStatus: string; family: string; phaseNote: string;
  rollout: RolloutEntry[]; _search?: string; _phaseStart?: string;
  /* R115 [S11b]: which source carries this record. `framework` for the 430
     the controlled document defines, `plan-defined` for the ten the plan
     defines and the document does not. Set by the generator from the file
     that supplies them, so it cannot be edited apart from the records. */
  provenance: string;
  /* R235: set on the metrics whose base-case maturity value does not meet the
     source target, with the reason and a pointer to where it is written up.
     The maturity-closure check exempts exactly the records carrying it, and
     fails if one of them starts meeting its target. */
  documentedGap?: string; documentedGapSection?: string;
}
export interface QualityPhase { id: string; anchor: string; purpose: string; scope?: string; exitEvidence?: string; }
export interface QualityGate { id: string; decision: string; name?: string; floor?: string; evidence?: string; fallback?: string; }
export interface CpFamily { id: string; domain: string; records: number; owners?: string; sensitivity?: string; }
export interface QualityData {
  source: string; counts: { KPP: number; TPP: number; CP: number; total: number };
  /* R115 [S11b]: how many of `total` each source carries, and the one
     sentence every surface describing the catalog must use. R220 in S12 and
     S16 land on the same words by reading this, not by copying it. */
  provenance: { framework: number; planDefined: number; planDefinedIds: string[]; note: string };
  concepts: string[]; cpFamilies?: CpFamily[]; phases: QualityPhase[]; gates: QualityGate[]; parameters: QualityParameter[];
}

export const NHA_QUALITY_DATA = '''
TS_FOOTER = " as unknown as QualityData;\n"


CONCEPTS = [
    "Coverage, affordability & eligibility",
    "Access, routing & unit network",
    "Quality, safety & patient experience",
    "Equity, rights & legitimacy",
    "Workforce & care delivery",
    "Claims, payments & financing",
    "Hospitals & regional delivery",
    "Medicines, devices & supply",
    "Expanded benefits & public health",
    "Data, cybersecurity & AI",
    "Governance, transition & continuity",
    "Research, innovation & training",
    "Population, macroeconomics & offsets",
]


TPP_CONCEPTS = {
    "1": CONCEPTS[0],
    "2": CONCEPTS[5],
    "3": CONCEPTS[7],
    "4": CONCEPTS[7],
    "5": CONCEPTS[6],
    "6": CONCEPTS[1],
    "7": CONCEPTS[1],
    "8": CONCEPTS[4],
    "9": CONCEPTS[8],
    "10": CONCEPTS[9],
    "11": CONCEPTS[9],
    "12": CONCEPTS[10],
    "13": CONCEPTS[11],
    "EMP": CONCEPTS[10],
    "LEG": CONCEPTS[3],
    "USE": CONCEPTS[3],
    "TRIB": CONCEPTS[3],
    "REG": CONCEPTS[10],
    "FORM": CONCEPTS[10],
}


CP_CONCEPTS = {
    "CP-TOT": CONCEPTS[12],
    "CP-POP": CONCEPTS[12],
    "CP-CLM": CONCEPTS[5],
    "CP-HOSP": CONCEPTS[6],
    "CP-CLIN": CONCEPTS[4],
    "CP-UNIT": CONCEPTS[1],
    "CP-LTC": CONCEPTS[8],
    "CP-RX": CONCEPTS[7],
    "CP-DX": CONCEPTS[7],
    "CP-BH": CONCEPTS[8],
    "CP-DVH": CONCEPTS[8],
    "CP-EMS": CONCEPTS[8],
    "CP-PH": CONCEPTS[8],
    "CP-IT": CONCEPTS[9],
    "CP-GOV": CONCEPTS[10],
    "CP-RD": CONCEPTS[11],
    "CP-EDU": CONCEPTS[11],
    "CP-TRN": CONCEPTS[10],
    "CP-FIN": CONCEPTS[5],
    "CP-OFF": CONCEPTS[12],
}


def clean(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def table_rows(table) -> list[dict[str, str]]:
    headers = [clean(cell.text) for cell in table.rows[0].cells]
    return [
        {header: clean(cell.text) for header, cell in zip(headers, row.cells)}
        for row in table.rows[1:]
    ]


def kpp_concept(domain: str) -> str:
    key = domain.lower()
    if key.startswith("coverage"):
        return CONCEPTS[0]
    if key.startswith("access"):
        return CONCEPTS[1]
    if key.startswith("quality") or key.startswith("safety"):
        return CONCEPTS[2]
    if key.startswith("equity") or key.startswith("legitimacy"):
        return CONCEPTS[3]
    if key.startswith("workforce"):
        return CONCEPTS[4]
    if key.startswith("cost"):
        return CONCEPTS[5]
    if key.startswith("transition"):
        return CONCEPTS[10]
    return CONCEPTS[10]


def tpp_key(identifier: str) -> str:
    suffix = identifier.removeprefix("TPP-")
    match = re.match(r"(\d+|[A-Z]+)", suffix)
    if not match:
        raise ValueError(f"Unrecognized TPP identifier: {identifier}")
    return match.group(1)


def source_rows(document: Document) -> tuple[list[dict], list[dict], list[dict]]:
    kpps = []
    for row in table_rows(document.tables[114]):
        kpps.append(
            {
                "id": row["ID"],
                "type": "KPP",
                "name": row["Metric"],
                "concept": kpp_concept(row["Domain / trace"]),
                "where": row["Domain / trace"],
                "target": row["Source target"],
                "calculation": row["Calculation contract"],
                "datasets": row["Datasets"],
                "ownerVerifier": row["Owner / verifier"],
                "status": row["Status"],
                "unit": "",
                "modelRole": "performance outcome",
                "temporal": "maturity target",
                "unitStatus": "",
                "family": "",
            }
        )

    tpps = []
    for row in table_rows(document.tables[116]):
        identifier = row["ID"]
        concept = TPP_CONCEPTS[tpp_key(identifier)]
        tpps.append(
            {
                "id": identifier,
                "type": "TPP",
                "name": row["Metric"],
                "concept": concept,
                "where": concept,
                "target": row["Source target"],
                "calculation": row["Calculation / unit"],
                "datasets": row["Datasets"],
                "ownerVerifier": row["Owner / verifier"],
                "status": row["Status"],
                "unit": "",
                "modelRole": "technical performance",
                "temporal": "maturity target",
                "unitStatus": "",
                "family": "",
            }
        )

    family_rows = table_rows(document.tables[120])
    family_by_id = {row["Family"]: row for row in family_rows}
    cps = []
    for table_index, family_row in zip(range(121, 141), family_rows):
        family = family_row["Family"]
        expected = int(family_row["Records"])
        rows = table_rows(document.tables[table_index])
        if len(rows) != expected:
            raise ValueError(
                f"{family}: expected {expected} records, extracted {len(rows)}"
            )
        for row in rows:
            definition = row["Definition"]
            name = definition.split(" — ", 1)[0]
            cps.append(
                {
                    "id": row["ID"],
                    "type": "CP",
                    "name": name,
                    "concept": CP_CONCEPTS[family],
                    "where": family_row["Domain"],
                    "target": row["Value/source status"],
                    "calculation": definition,
                    "datasets": "",
                    "ownerVerifier": family_row["Accountable owner(s)"],
                    "status": row["Value/source status"],
                    "unit": row["Canonical unit"],
                    "modelRole": row["Model role"],
                    "temporal": row["Temporal"],
                    "unitStatus": row["Unit status"],
                    "family": family,
                }
            )
    return kpps, tpps, cps


def phase_records(document: Document) -> list[dict]:
    records = []
    for row in table_rows(document.tables[483]):
        records.append(
            {
                "id": row["ID"].replace("PH-", ""),
                "anchor": row["Anchor"],
                "purpose": row["Purpose"],
                "scope": row["Controlled products / scope"],
                "exitEvidence": row["Exit evidence"],
            }
        )
    return records


def gate_records(document: Document) -> list[dict]:
    return [
        {
            "id": row["ID"].replace("PH-", ""),
            "name": row["Gate"],
            "decision": row["Decision point"],
            "floor": row["Blocking floor / condition"],
            "evidence": row["Evidence / trace"],
            "fallback": row["Fallback / repair"],
        }
        for row in table_rows(document.tables[485])
    ]


# R121 [S2]: which phases each gate's progression floor governs, declared with
# the gate's own decision point as its warrant.  This was an undocumented inline
# dict mapping every gate to exactly one phase, and Gate 1 was the case where
# one phase is the wrong answer: its decision point names a transition, so its
# floor is both the exit condition of P3 and the entry condition of P4.  Writing
# it to P4 alone left the Data tab declaring a framework target at P3 that the
# catalog could not confirm -- the seventeenth of R117's claims, and the only one
# that did not resolve.  The other four decision points name an event rather
# than a boundary, so each governs the single phase that event belongs to.
#
# The decision text is quoted from the framework's gate table (the same table
# gate_records reads) so that a reader can check the mapping against its source
# without opening the DOCX.
GATE_PHASES: dict[str, tuple[tuple[str, ...], str]] = {
    "PH-G1": (("P3", "P4"), "Before major expansion and specifically PH-P3 to PH-P4"),
    "PH-G2": (("P6",), "Before broad cost-sharing elimination, which P6 carries out"),
    "PH-G3": (("P7",), "Before full expanded-benefit rollout, which P7 carries out"),
    "PH-G4": (("P8",), "Before mature full-benefit/maturity certification, which is P8"),
    "PH-G5": (("P8",), "Before national AI-assisted routing, reached at maturity"),
}


def target_overrides(document: Document) -> dict[str, list[dict]]:
    overrides: dict[str, list[dict]] = {}
    for row in table_rows(document.tables[486]):
        match = re.match(r"(KPP|TPP)-[A-Z0-9.]+", row["Mature target"])
        if not match:
            raise ValueError(f"Cannot identify parameter in {row['Mature target']}")
        identifier = match.group(0)
        if row["Gate"] not in GATE_PHASES:
            raise ValueError(f"No declared phase for gate {row['Gate']}")
        phases, _warrant = GATE_PHASES[row["Gate"]]
        for phase in phases:
            overrides.setdefault(identifier, []).append(
                {
                    "phase": phase,
                    "gate": row["Gate"].replace("PH-", ""),
                    "value": row["Progression floor"],
                    "kind": "progression floor",
                    "interpretation": row["Interpretation"],
                }
            )

    # The roadmap establishes one additional numeric phase milestone before G2.
    overrides.setdefault("KPP-B7", []).insert(
        0,
        {
            "phase": "P5",
            "gate": "",
            "value": ">=65% by phase end",
            "kind": "phase milestone",
            "interpretation": "P5 delivery-scale milestone from the controlled phase plan.",
        },
    )

    # The other half of R121: two DIFFERENT gates writing a floor to the same
    # phase for the same parameter would merge two requirements into one
    # indistinguishable row.  Measured 2026-08-16, it does not happen -- G4 and
    # G5 share P8 but not a parameter (G4 writes KPP-C5 and KPP-C6, G5 writes
    # TPP-11.5), and every row keeps the gate that produced it.  The row's
    # premise that the collapse merges two gates' floors is not what the data
    # does; this keeps it that way.
    for identifier, rows in overrides.items():
        by_phase: dict[str, set[str]] = {}
        for entry in rows:
            by_phase.setdefault(entry["phase"], set()).add(entry["gate"])
        for phase, gates in sorted(by_phase.items()):
            if len(gates) > 1:
                raise ValueError(
                    f"{identifier} receives floors from {sorted(gates)} at {phase}: "
                    "two gates cannot write one undistinguished floor"
                )
    return overrides


def apply_house_style(parameter: dict) -> None:
    """Rewrite the DOCX's forms into the ones the dashboard publishes.

    Declared rather than done by hand, because a hand pass is exactly what made
    the live catalog unreproducible.
    """
    for field, (docx_form, published_form) in HOUSE_STYLE.items():
        value = parameter.get(field)
        if isinstance(value, str) and docx_form in value:
            parameter[field] = value.replace(docx_form, published_form, 1)
    for (identifier, field), (before, after) in WORDING.items():
        if parameter["id"] == identifier:
            parameter[field] = parameter[field].replace(before, after)


DOCUMENTED_GAP_SECTION = (
    "research/quality-equation-methodology.md"
    "#documented-gaps-the-model-refuses-to-hide"
)

# R235 [S3]: the metrics whose base-case maturity value does not meet the
# source target, and why.
#
# This lived as `const documentedGap = { 'KPP-C1': true, 'KPP-C8': true }`
# inside the maturity-closure check.  The audit calls it the most honest thing
# in the codebase, and it was: the model does not reach two of its own targets
# and the code said so, by ID, with a pointer to where it is written up.
#
# The problem was where it lived.  An exemption held inside the test it
# exempts from cannot be seen by anyone reading the catalog, and it persists
# silently if the gap ever closes - the metric would start meeting its target
# and nothing would say the exemption was no longer needed.  Stamping it onto
# the record makes it a property of the parameter, carried wherever the
# parameter goes, and lets the check fail in BOTH directions.
DOCUMENTED_GAPS = {
    "KPP-C1": (
        "Health share of GDP: the fiscal engine, holding scale constant, computes "
        "about 18% at maturity against the 15.2% ambition, because the expanded "
        "benefits roughly offset the savings levers. The engine is not tuned to the "
        "ambition and reports the gap."
    ),
    "KPP-C7": (
        "Wealth-financing collection efficiency: the researched mature collection "
        "rate is 84% against a controlled 92% ambition, so the equation approaches "
        "84 and the gap is the distance between researched practice and the plan's "
        "target."
    ),
    "KPP-C8": (
        "Ordinary-taxpayer burden share: the base case computes 5.6% of program cost "
        "against the 5% cap, after wealth financing, household relief and wage "
        "pass-through, and 17 of the 20 scenarios breach it, the worst at 16.7% "
        "(SCN-PESS). R125 moved this and moved it the unflattering way: the wage "
        "pass-through was subtracted from the burden at its gross value while the "
        "28% tax feedback on those same wages had already been credited against "
        "the revenue requirement, so households were relieved twice for the taxed "
        "share and the base case read 4.6%, inside the cap. Corrected to the wage "
        "gain households keep, the base case is outside the cap too. R143 moved it "
        "earlier: before the healthcare model grew the wealth base at the sourced "
        "top-capital rate rather than at GDP, the base case computed about 5.9%."
    ),
    "TPP-W1": (
        "Role-region vacancy ceiling: the error form closes only where its build "
        "state reaches 1, and this one averages infrastructure with the workforce "
        "sufficiency index, whose own controlled target is 98% rather than 100%. The "
        "plan's sufficiency ambition leaves the vacancy ceiling about a third of a "
        "point short."
    ),
}


def stamp_documented_gaps(parameters: list[dict]) -> None:
    """Attach each declared gap to its record, and fail on a stale id."""
    by_id = {item["id"]: item for item in parameters}
    missing = sorted(set(DOCUMENTED_GAPS) - set(by_id))
    if missing:
        raise ValueError(f"DOCUMENTED_GAPS names records not in the catalog: {missing}")
    for identifier, reason in DOCUMENTED_GAPS.items():
        by_id[identifier]["documentedGap"] = reason
        by_id[identifier]["documentedGapSection"] = DOCUMENTED_GAP_SECTION


# R115 [S11b]: the ten records the DOCX does not carry, marked structurally.
#
# The row says "add them to the controlled source or mark them provisional",
# and both the prompt and two handoffs said nothing identified WHICH ten.
# Measured: the addendum names all ten by id, and in the live catalog all ten
# carry a `status` string no other record carries.  So they were identifiable
# twice over and nothing read either signal.  A status string is prose that a
# regeneration could reword; `provenance` is the fact, set here from the file
# that defines it, so the ten cannot drift from the ten.
#
# Not "provisional".  These are not draft numbers - they are the plan's own
# parameters, with targets, calculations, datasets and verifiers like any
# other.  What is true of them is narrower and it is about the SOURCE: the
# framework document does not carry them.  `plan-defined` says that; the 430
# are `framework`.
#
# CATALOG_PROVENANCE_NOTE is the wording the page must use.  R220 in S12 fixes
# the page that calls all 440 "controlled" and S16 owns the vocabulary, and
# the prompt requires all three to land on the same words.  Exported as data
# rather than written up for copying, because copying prose between three
# sections is how three sections end up saying three things.
PROVENANCE_FRAMEWORK = "framework"
PROVENANCE_PLAN = "plan-defined"

CATALOG_PROVENANCE_NOTE = (
    "430 of these records are carried by the controlled framework document. "
    "Ten are not: the merit health-talent immigration parameters, which the "
    "plan defines and the framework document does not contain. They are "
    "listed here with the rest and marked plan-defined, because leaving them "
    "out would understate what the plan commits to and calling all 440 "
    "controlled would overstate what the framework carries."
)


def load_addendum() -> list[dict]:
    """The records that are not in the DOCX, in the order the live file has them."""
    payload = json.loads(ADDENDUM.read_text(encoding="utf-8"))
    records = payload["records"]
    for record in records:
        record["provenance"] = PROVENANCE_PLAN
    return records


def build_catalog() -> dict:
    document = Document(SOURCE)
    kpps, tpps, cps = source_rows(document)
    overrides = target_overrides(document)
    parameters = kpps + tpps + cps

    for parameter in parameters:
        if parameter["type"] in {"KPP", "TPP"}:
            rollout = list(overrides.get(parameter["id"], []))
            rollout.append(
                {
                    "phase": "P8",
                    "gate": "",
                    "value": parameter["target"],
                    "kind": "maturity target",
                    "interpretation": "Controlled source target assessed at maturity.",
                }
            )
            parameter["rollout"] = rollout
            parameter["phaseNote"] = (
                "No numeric interim target is specified unless an earlier phase "
                "milestone or gate floor appears below."
            )
        else:
            parameter["rollout"] = []
            parameter["phaseNote"] = (
                "Cost/model parameter, not a phase performance target. "
                "The framework does not assign phase-specific values."
            )

    for parameter in parameters:
        apply_house_style(parameter)

    identifiers = [item["id"] for item in parameters]
    if len(identifiers) != len(set(identifiers)):
        raise ValueError("Duplicate parameter identifier found")
    if (len(kpps), len(tpps), len(cps), len(parameters)) != (41, 79, 310, 430):
        raise ValueError(
            "Unexpected catalog counts: "
            f"{len(kpps)} KPP, {len(tpps)} TPP, {len(cps)} CP"
        )

    for parameter in parameters:
        parameter["provenance"] = PROVENANCE_FRAMEWORK

    parameters.extend(load_addendum())
    kpp_total = sum(1 for item in parameters if item["type"] == "KPP")
    tpp_total = sum(1 for item in parameters if item["type"] == "TPP")
    identifiers = [item["id"] for item in parameters]
    if len(identifiers) != len(set(identifiers)):
        raise ValueError("Addendum reuses an identifier the DOCX already defines")

    stamp_documented_gaps(parameters)

    family_rows = table_rows(document.tables[120])
    return {
        "source": "National Health Assurance Framework v2.0.0 FINAL",
        "counts": {
            "KPP": kpp_total,
            "TPP": tpp_total,
            "CP": len(cps),
            "total": len(parameters),
        },
        "provenance": {
            "framework": sum(
                1 for item in parameters
                if item["provenance"] == PROVENANCE_FRAMEWORK
            ),
            "planDefined": sum(
                1 for item in parameters if item["provenance"] == PROVENANCE_PLAN
            ),
            "planDefinedIds": [
                item["id"] for item in parameters
                if item["provenance"] == PROVENANCE_PLAN
            ],
            "note": CATALOG_PROVENANCE_NOTE,
        },
        "concepts": CONCEPTS,
        "cpFamilies": [
            {
                "id": row["Family"],
                "domain": row["Domain"],
                "records": int(row["Records"]),
                "owners": row["Accountable owner(s)"],
                "sensitivity": row["Primary sensitivity group"],
            }
            for row in family_rows
        ],
        "phases": phase_records(document),
        "gates": gate_records(document),
        "parameters": parameters,
    }


def render() -> str:
    catalog = build_catalog()
    payload = json.dumps(catalog, ensure_ascii=False, separators=(",", ":"))
    if "—" in payload:
        raise ValueError("Em dash survived the house-style pass")
    return TS_HEADER + payload + TS_FOOTER


def main() -> None:
    text = render()
    # Platform line endings on purpose: git normalises to LF in the index, and
    # writing LF here would leave the whole file dirty in a Windows worktree.
    OUTPUT.write_text(text, encoding="utf-8")
    counts = json.loads(
        text[text.index(TS_HEADER) + len(TS_HEADER) : -len(TS_FOOTER)]
    )["counts"]
    print(
        f"Wrote {OUTPUT.relative_to(ROOT)}: "
        f"{counts['KPP']} KPP + {counts['TPP']} TPP + "
        f"{counts['CP']} CP = {counts['total']} records"
    )


if __name__ == "__main__":
    main()
